### ISSUE TITLE
Client request failed

### ISSUE THREAD

**Issue by luozhouyang** [OpenNMT/OpenNMT-tf#124]
Hey guys.
I build tensorflow serving and export a model. Then I ran it on a container:
```bash
allen@ubuntu-linux:~/opennmt$ docker run -ti --name serving --volume /home/allen/models/export/manual/:/root/models/ -p 10000:10000 xxxx/serving:0.2
2018-05-17 12:19:59.740963: I tensorflow_serving/model_servers/main.cc:152] Building single TensorFlow model file config:  model_name: address model_base_path: /root/models
2018-05-17 12:19:59.776360: I tensorflow_serving/model_servers/server_core.cc:444] Adding/updating models.
2018-05-17 12:19:59.776693: I tensorflow_serving/model_servers/server_core.cc:499]  (Re-)adding model: address
2018-05-17 12:19:59.925146: I tensorflow_serving/core/basic_manager.cc:716] Successfully reserved resources to load servable {name: address version: 1526523975}
2018-05-17 12:19:59.925261: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: address version: 1526523975}
2018-05-17 12:19:59.925306: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: address version: 1526523975}
2018-05-17 12:19:59.925988: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /root/models/1526523975
2018-05-17 12:19:59.926127: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:242] Loading SavedModel with tags: { serve }; from: /root/models/1526523975
2018-05-17 12:20:00.157636: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:161] Restoring SavedModel bundle.
2018-05-17 12:20:03.578998: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:196] Running LegacyInitOp on SavedModel bundle.
2018-05-17 12:20:03.967743: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:291] SavedModel load for tags { serve }; Status: success. Took 4041580 microseconds.
2018-05-17 12:20:03.971681: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: address version: 1526523975}
2018-05-17 12:20:04.011089: I tensorflow_serving/model_servers/main.cc:315] Running ModelServer at 0.0.0.0:10000 ...
```   
It seems ok.
But when I ran the nmt_client.py, it failed:
```bash
python nmt_client.py --model_name address --port 10000
Traceback (most recent call last):
  File "nmt_client.py", line 86, in <module>
    main()
  File "nmt_client.py", line 81, in main
    result = parse_translation_result(future.result())
  File "/home/allen/PycharmProjects/Address/venv2/local/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 97, in result
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.ExpirationError: ExpirationError(code=StatusCode.DEADLINE_EXCEEDED, details="Deadline Exceeded")
```  
I installed grpcio and tensorflow-serving-api as the tensorflow serving tutorial.
Any ideas?

**Comment by guillaumekln** [comment]
Hello,

Maybe the translation just took too much time? Try increasing the default timeout with the `--timeout` option (defaults to 10 seconds).

**Comment by luozhouyang** [comment]
Thanks! Increasing timeout works!
