### ISSUE TITLE
Weird crash after training a while

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#144]
While I was trainig the date translation. After a While I got this crash.

I'm using features 

source_inputter=onmt.inputters.ParallelInputter([onmt.inputters.WordEmbedder(
            vocabulary_file_key="source_chars_vocabulary",
            embedding_size=300,
            tokenizer=CharacterTokenizer(configuration_file_or_key=None)),
            onmt.inputters.WordEmbedder(
                vocabulary_file_key="feature_1_vocabulary",
                embedding_file_key='feature_1_embbeding',
                embedding_size=None,
                embedding_file_with_header=False,
                tokenizer=CharacterTokenizer(configuration_file_or_key=None),
                trainable=False)]
            , reducer=onmt.layers.ConcatReducer()),

I'm not sure if you need the data, but this time the data weights more than 200mb so its a little big.
As you can see It was training. the loss was already around 0.0016

2018-06-04 19:14:40.616572: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Creating model directory model
INFO:tensorflow:Using config: {'_model_dir': 'model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': 500, '_save_checkpoints_secs': None, '_session_config': gpu_options {
  allow_growth: true
}
allow_soft_placement: true
, '_keep_checkpoint_max': 2, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x10b883c18>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Number of trainable parameters: 3463951
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
2018-06-04 19:15:09.844883: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:94] Filling up shuffle buffer (this may take a while): 2985964 of 10000000
2018-06-04 19:15:19.844619: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:94] Filling up shuffle buffer (this may take a while): 4620500 of 10000000
2018-06-04 19:15:29.845116: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:94] Filling up shuffle buffer (this may take a while): 6255486 of 10000000
2018-06-04 19:15:39.438359: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:129] Shuffle buffer filled.
INFO:tensorflow:Saving checkpoints for 1 into model/model.ckpt.
INFO:tensorflow:loss = 35.371643, step = 1
INFO:tensorflow:global_step/sec: 0.741452
INFO:tensorflow:loss = 8.236523, step = 101 (134.875 sec)
INFO:tensorflow:global_step/sec: 0.758491
INFO:tensorflow:words_per_sec/features: 1720.03
INFO:tensorflow:words_per_sec/labels: 1321.74
INFO:tensorflow:loss = 3.814239, step = 201 (131.841 sec)
INFO:tensorflow:global_step/sec: 0.776194
INFO:tensorflow:words_per_sec/features: 1729.14
INFO:tensorflow:words_per_sec/labels: 1333.94
INFO:tensorflow:loss = 0.23172447, step = 301 (128.836 sec)
INFO:tensorflow:global_step/sec: 0.764725
INFO:tensorflow:words_per_sec/features: 1722.34
INFO:tensorflow:words_per_sec/labels: 1332.29
INFO:tensorflow:loss = 0.11639896, step = 401 (130.766 sec)
INFO:tensorflow:Saving checkpoints for 501 into model/model.ckpt.
INFO:tensorflow:global_step/sec: 0.759756
INFO:tensorflow:words_per_sec/features: 1704.39
INFO:tensorflow:words_per_sec/labels: 1308.05
INFO:tensorflow:loss = 0.48187032, step = 501 (131.614 sec)
INFO:tensorflow:global_step/sec: 0.762904
INFO:tensorflow:words_per_sec/features: 1727.22
INFO:tensorflow:words_per_sec/labels: 1325.08
INFO:tensorflow:loss = 0.11274391, step = 601 (131.084 sec)
INFO:tensorflow:global_step/sec: 0.754339
INFO:tensorflow:words_per_sec/features: 1701.58
INFO:tensorflow:words_per_sec/labels: 1310.22
INFO:tensorflow:loss = 0.012174034, step = 701 (132.564 sec)
INFO:tensorflow:global_step/sec: 0.768359
INFO:tensorflow:words_per_sec/features: 1714.88
INFO:tensorflow:words_per_sec/labels: 1335.07
INFO:tensorflow:loss = 0.12615848, step = 801 (130.142 sec)
INFO:tensorflow:global_step/sec: 0.759886
INFO:tensorflow:words_per_sec/features: 1711.57
INFO:tensorflow:words_per_sec/labels: 1321.69
INFO:tensorflow:loss = 0.08066821, step = 901 (131.604 sec)
INFO:tensorflow:Saving checkpoints for 1001 into model/model.ckpt.
INFO:tensorflow:global_step/sec: 0.756596
INFO:tensorflow:words_per_sec/features: 1697.27
INFO:tensorflow:words_per_sec/labels: 1315.02
INFO:tensorflow:loss = 0.16781883, step = 1001 (132.166 sec)
INFO:tensorflow:global_step/sec: 0.765437
INFO:tensorflow:words_per_sec/features: 1727.64
INFO:tensorflow:words_per_sec/labels: 1317.16
INFO:tensorflow:loss = 0.064965464, step = 1101 (130.652 sec)
INFO:tensorflow:global_step/sec: 0.775379
INFO:tensorflow:words_per_sec/features: 1741.81
INFO:tensorflow:words_per_sec/labels: 1331.86
INFO:tensorflow:loss = 0.22979628, step = 1201 (128.970 sec)
INFO:tensorflow:global_step/sec: 0.76189
INFO:tensorflow:words_per_sec/features: 1717.99
INFO:tensorflow:words_per_sec/labels: 1326.5
INFO:tensorflow:loss = 0.012813177, step = 1301 (131.250 sec)
INFO:tensorflow:global_step/sec: 0.767135
INFO:tensorflow:words_per_sec/features: 1725.67
INFO:tensorflow:words_per_sec/labels: 1318.55
INFO:tensorflow:loss = 0.0019420229, step = 1401 (130.358 sec)
INFO:tensorflow:Saving checkpoints for 1501 into model/model.ckpt.
INFO:tensorflow:global_step/sec: 0.747556
INFO:tensorflow:words_per_sec/features: 1696.91
INFO:tensorflow:words_per_sec/labels: 1296.95
INFO:tensorflow:loss = 0.12263468, step = 1501 (133.760 sec)
INFO:tensorflow:global_step/sec: 0.77986
INFO:tensorflow:words_per_sec/features: 1749.57
INFO:tensorflow:words_per_sec/labels: 1343.2
INFO:tensorflow:loss = 0.014319618, step = 1601 (128.234 sec)
INFO:tensorflow:global_step/sec: 0.761456
INFO:tensorflow:words_per_sec/features: 1712.85
INFO:tensorflow:words_per_sec/labels: 1324.52
INFO:tensorflow:loss = 0.020468647, step = 1701 (131.330 sec)
INFO:tensorflow:global_step/sec: 0.775392
INFO:tensorflow:words_per_sec/features: 1732.88
INFO:tensorflow:words_per_sec/labels: 1331.41
INFO:tensorflow:loss = 0.0024468224, step = 1801 (128.964 sec)
INFO:tensorflow:global_step/sec: 0.767931
INFO:tensorflow:words_per_sec/features: 1739.28
INFO:tensorflow:words_per_sec/labels: 1338.34
INFO:tensorflow:loss = 0.005562725, step = 1901 (130.220 sec)
INFO:tensorflow:Saving checkpoints for 2001 into model/model.ckpt.
INFO:tensorflow:global_step/sec: 0.764808
INFO:tensorflow:words_per_sec/features: 1707.71
INFO:tensorflow:words_per_sec/labels: 1315.89
INFO:tensorflow:loss = 0.008396647, step = 2001 (130.747 sec)
INFO:tensorflow:global_step/sec: 0.761122
INFO:tensorflow:words_per_sec/features: 1717.89
INFO:tensorflow:words_per_sec/labels: 1327.17
INFO:tensorflow:loss = 0.0015771925, step = 2101 (131.386 sec)
INFO:tensorflow:global_step/sec: 0.759416
INFO:tensorflow:words_per_sec/features: 1699.93
INFO:tensorflow:words_per_sec/labels: 1325.99
INFO:tensorflow:loss = 0.0054187467, step = 2201 (131.687 sec)
INFO:tensorflow:global_step/sec: 0.77499
INFO:tensorflow:words_per_sec/features: 1743.83
INFO:tensorflow:words_per_sec/labels: 1332.7
INFO:tensorflow:loss = 0.11013239, step = 2301 (129.029 sec)
INFO:tensorflow:global_step/sec: 0.771551
INFO:tensorflow:words_per_sec/features: 1742.74
INFO:tensorflow:words_per_sec/labels: 1325.94
INFO:tensorflow:loss = 0.0073208287, step = 2401 (129.611 sec)
INFO:tensorflow:Saving checkpoints for 2501 into model/model.ckpt.
INFO:tensorflow:global_step/sec: 0.759122
INFO:tensorflow:words_per_sec/features: 1705.56
INFO:tensorflow:words_per_sec/labels: 1315.57
INFO:tensorflow:loss = 0.002323056, step = 2501 (131.730 sec)
INFO:tensorflow:global_step/sec: 0.758114
INFO:tensorflow:words_per_sec/features: 1712.54
INFO:tensorflow:words_per_sec/labels: 1317.55
INFO:tensorflow:loss = 0.00046854082, step = 2601 (131.908 sec)
INFO:tensorflow:global_step/sec: 0.773016
INFO:tensorflow:words_per_sec/features: 1730.09
INFO:tensorflow:words_per_sec/labels: 1327.91
INFO:tensorflow:loss = 0.045485895, step = 2701 (129.363 sec)
INFO:tensorflow:global_step/sec: 0.762782
INFO:tensorflow:words_per_sec/features: 1717.78
INFO:tensorflow:words_per_sec/labels: 1327.76
INFO:tensorflow:loss = 0.0009326099, step = 2801 (131.099 sec)
INFO:tensorflow:global_step/sec: 0.771935
INFO:tensorflow:words_per_sec/features: 1734.46
INFO:tensorflow:words_per_sec/labels: 1324.88
INFO:tensorflow:loss = 0.13372216, step = 2901 (129.545 sec)
INFO:tensorflow:Saving checkpoints for 3001 into model/model.ckpt.
INFO:tensorflow:global_step/sec: 0.750862
INFO:tensorflow:words_per_sec/features: 1688.1
INFO:tensorflow:words_per_sec/labels: 1310.13
INFO:tensorflow:loss = 0.002269319, step = 3001 (133.175 sec)
INFO:tensorflow:global_step/sec: 0.770498
INFO:tensorflow:words_per_sec/features: 1723.06
INFO:tensorflow:words_per_sec/labels: 1339.9
INFO:tensorflow:loss = 0.0016218458, step = 3101 (129.791 sec)
Traceback (most recent call last):
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: All dimensions except 2 must match. Input 1 has shape [128 27 5] and doesn't match input 0 with shape [128 28 300].
	 [[Node: optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/ConcatOffset = ConcatOffset[N=2, _class=["loc:@seq2seq/parallel_0/seq2seq/encoder/concat"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/mod, optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/ShapeN, optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/ShapeN:1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/src/date_Translation/train_and_eval.py", line 35, in <module>
    main()
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/src/date_Translation/train_and_eval.py", line 33, in main
    nnmtMain()
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/bin/main.py", line 123, in main
    runner.train()
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/runner.py", line 149, in train
    train_spec.input_fn, hooks=train_spec.hooks, max_steps=train_spec.max_steps)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 859, in _train_model_default
    saving_listeners)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1059, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 567, in run
    run_metadata=run_metadata)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1043, in run
    run_metadata=run_metadata)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1134, in run
    raise six.reraise(*original_exc_info)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1119, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1191, in run
    run_metadata=run_metadata)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 971, in run
    return self._sess.run(*args, **kwargs)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: All dimensions except 2 must match. Input 1 has shape [128 27 5] and doesn't match input 0 with shape [128 28 300].
	 [[Node: optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/ConcatOffset = ConcatOffset[N=2, _class=["loc:@seq2seq/parallel_0/seq2seq/encoder/concat"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/mod, optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/ShapeN, optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/ShapeN:1)]]

Caused by op 'optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/ConcatOffset', defined at:
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/src/date_Translation/train_and_eval.py", line 35, in <module>
    main()
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/src/date_Translation/train_and_eval.py", line 33, in main
    nnmtMain()
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/bin/main.py", line 123, in main
    runner.train()
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/runner.py", line 149, in train
    train_spec.input_fn, hooks=train_spec.hooks, max_steps=train_spec.max_steps)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 363, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 843, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 856, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/models/model.py", line 106, in _model_fn
    train_op = optimize(loss, params)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/utils/optim.py", line 143, in optimize
    colocate_gradients_with_ops=True)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/optimizers.py", line 241, in optimize_loss
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 526, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 494, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 636, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 385, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 636, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/ops/array_grad.py", line 224, in _ConcatGradV2
    op, grad, start_value_index=0, end_value_index=-1, dim_index=-1)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/ops/array_grad.py", line 150, in _ConcatGradHelper
    offset = gen_array_ops.concat_offset(non_neg_concat_dim, sizes)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 884, in concat_offset
    "ConcatOffset", concat_dim=concat_dim, shape=shape, name=name)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'seq2seq/parallel_0/seq2seq/encoder/concat', defined at:
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/src/date_Translation/train_and_eval.py", line 35, in <module>
    main()
[elided 6 identical lines from previous traceback]
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 831, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/models/model.py", line 103, in _model_fn
    _loss_op, features_shards, labels_shards, params, mode, config)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/utils/parallel.py", line 145, in __call__
    outputs.append(funs[i](*args[i], **kwargs[i]))
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/models/model.py", line 66, in _loss_op
    logits, _ = self._build(features, labels, params, mode, config=config)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/models/sequence_to_sequence.py", line 114, in _build
    log_dir=log_dir)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/inputters/inputter.py", line 194, in transform_data
    inputs = self._transform_data(data, mode)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/inputters/inputter.py", line 337, in _transform_data
    transformed = self.reducer.reduce(transformed)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/opennmt/layers/reducer.py", line 172, in reduce
    return tf.concat(inputs, self.axis)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1189, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 953, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/sergio/cognitive/NaturalLanguageRecognition/NaturalLanguageManager/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): All dimensions except 2 must match. Input 1 has shape [128 27 5] and doesn't match input 0 with shape [128 28 300].
	 [[Node: optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/ConcatOffset = ConcatOffset[N=2, _class=["loc:@seq2seq/parallel_0/seq2seq/encoder/concat"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/mod, optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/ShapeN, optim/gradients/seq2seq/parallel_0/seq2seq/encoder/concat_grad/ShapeN:1)]]

Process finished with exit code 1

**Comment by guillaumekln** [comment]
Are you training with multiple GPUs?

**Comment by lockder** [comment]
Only cpu, because Im just testing 

Enviado desde mi iPhone

**Comment by guillaumekln** [comment]
Are you still facing this issue?

**Comment by lockder** [comment]
no
