### ISSUE TITLE
"score"  run_type fails with TypeError

### ISSUE THREAD

**Issue by melindaloubser1** [OpenNMT/OpenNMT-tf#236]
Tensorflow version = tensorflow-gpu 1.11.0
OpenNMT version = latest, pulled 18/10/2018 
4 GPUS with 6gb memory

I am training a basic NMT model using the configs  and model definition attached. Train_and_eval and infer run types both succeed, but after there is a trained model and inferred translation, scoring fails with a TypeError: 
```
Traceback (most recent call last):
  File "/home/ctext/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 527, in make_tensor_proto
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/ctext/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 527, in <listcomp>
    str_values = [compat.as_bytes(x) for x in proto_values]
  File "/home/ctext/.local/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 61, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got {'logits': <tf.Tensor 'seq2seq/decoder_1/cond/Merge:0' shape=(?, ?, 50001) dtype=float32>, 'attention': <tf.Tensor 'seq2seq/decoder_1/cond_1/Merge:0' shape=(?, ?, ?) dtype=float32>}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/onmt-main", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/opennmt/bin/main.py", line 175, in main
    checkpoint_path=args.checkpoint_path)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/runner.py", line 341, in score
    logits=logits, labels=labels["ids_out"])
  File "/home/ctext/.local/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 2045, in sparse_softmax_cross_entropy_with_logits
    logits = ops.convert_to_tensor(logits)
  File "/home/ctext/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1048, in convert_to_tensor
    as_ref=False)
  File "/home/ctext/.local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1144, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/ctext/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 228, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/ctext/.local/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 207, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/ctext/.local/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 531, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'dict'> to Tensor. Contents: {'logits': <tf.Tensor 'seq2seq/decoder_1/cond/Merge:0' shape=(?, ?, 50001) dtype=float32>, 'attention': <tf.Tensor 'seq2seq/decoder_1/cond_1/Merge:0' shape=(?, ?, ?) dtype=float32>}. Consider casting elements to a supported type.
```

The command used:
```
onmt-main score --model config/models/nmt_basic.py  \
--config config/data/af.yml config/training/basic.yml  \
--run_dir experiments/basic \
--num_gpus 4 \
--log_prediction_time \
--log_level DEBUG \
--checkpoint_path experiments/basic/models \
--features_file data/af/test.en \
--predictions_file experiments/basic/preds/test_preds.af \
>> experiments/preds/test_scores.txt
```
Since the error seems to come from tensorflow I am not sure if it is user error or something in OpenNMT or tensorflow causing it. Any help appreciated.

[configs.zip](https://github.com/OpenNMT/OpenNMT-tf/files/2491536/configs.zip)

**Comment by guillaumekln** [comment]
Could you check that you are actually running the latest OpenNMT-tf version? I think this issue was fixed in 0fac7a1f which is part of OpenNMT-tf 1.8.1.

**Comment by guillaumekln** [comment]
How did you install OpenNMT-tf initially? Looks like you use a mix of `pip` installation and `git clone`.

**Comment by melindaloubser1** [comment]
I installed it with pip first, but am running scripts in the git cloned directory. I apologise if this is the wrong way to do it; I wanted to run the examples first and it looked like that had to happen from the repo. Should I be doing it differently?

**Comment by guillaumekln** [comment]
I suggest only installing with `pip` unless you want to edit some code. I think an older code is running here.

**Comment by melindaloubser1** [comment]
Ok, I will try that. I checked the files that were changed in that commit; they do include the fix, but I'll see if the pip-only version works.

**Comment by melindaloubser1** [comment]
That solved it. Thank you for your help, I apologise for the confusion.

**Comment by melindaloubser1** [comment]
It appears I had two versions installed via pip, which explains a lot.
