### ISSUE TITLE
Error while using tensorflow serving example for translating transformer model

### ISSUE THREAD

**Issue by pranjali97** [OpenNMT/OpenNMT-tf#282]
Can the script at https://github.com/OpenNMT/OpenNMT-tf/blob/master/examples/serving/ende_client.py be used for translating results from the exported transformer model? 
I have received grpc error with
status = StatusCode.INVALID_ARGUMENT
details = "logits must be 2-dimensional
	 [[Node: transformer/encoder_1/layer_0/multi_head/Softmax = Softmax[T=DT_FLOAT, _output_shapes=[[?,8,?,?]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](transformer/encoder_1/layer_0/multi_head/add)]]"

Although the script seems to work fine for my other NMTBig model.

The complete traceback:
Traceback (most recent call last):
  File "transformer_client.py", line 95, in <module>
    main()
  File "transformer_client.py", line 20, in timed
    result = method(*args, **kw)
  File "transformer_client.py", line 89, in main
    result = parse_translation_result(future.result())
  File "/home/v/tfenv/lib/python3.4/site-packages/grpc/_channel.py", line 295, in result
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "logits must be 2-dimensional
	 [[Node: transformer/encoder_1/layer_0/multi_head/Softmax = Softmax[T=DT_FLOAT, _output_shapes=[[?,8,?,?]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](transformer/encoder_1/layer_0/multi_head/add)]]"
	debug_error_string = "{"created":"@1543583824.604823901","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1017,"grpc_message":"logits must be 2-dimensional\n\t [[Node: transformer/encoder_1/layer_0/multi_head/Softmax = Softmax[T=DT_FLOAT, _output_shapes=[[?,8,?,?]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](transformer/encoder_1/layer_0/multi_head/add)]]","grpc_status":3}"

**Comment by guillaumekln** [comment]
The [example](https://github.com/OpenNMT/OpenNMT-tf/blob/master/examples/serving/README.md) itself uses a Transformer model so it should work.

Can you give more details to reproduce the error?

**Comment by pranjali97** [comment]
Unlike the latest code, I am using the code where i am providing tokenized inputs for the translations, in the format [ ['My', 'name', 'is', 'x' ], ['I', 'like', 'onmt' ] ]. Other than that the code remains the same. 
My exported model is running using the tensorflow-model-server on the localhost itself.

**Comment by guillaumekln** [comment]
Can you run the example that I linked above?

**Comment by pranjali97** [comment]
Yes I’ll try that. Is the path to the sentencepiece_model same as the exported model path ? I don’t have the sentencepiece_model

**Comment by guillaumekln** [comment]
If are not using SentencePiece then you should adapt the client code.

**Comment by guillaumekln** [comment]
Closing due to lack of activity. Feel free to reopen it if you feel the issue has not been resolved.
