### ISSUE TITLE
Crash while using a mix of ParallelInputter, MixedInputter, ParalleEncoder

### ISSUE THREAD

**Issue by lockder** [OpenNMT/OpenNMT-tf#288]
the idea behind the model is to use
https://arxiv.org/pdf/1804.09849.pdf

but with features

the crash happens when I setup the selfAttentionEncoder with more than 1 layer.
the crash is about the scope of a variable. Its complaining about its the same name of variable and we are not telling them about the auto reuse

the model

```
return SequenceToSequence(source_inputter=ParallelInputter([MixedInputter([WordEmbedder(vocabulary_file_key="source_words_vocabulary",
                                                                                            embedding_size=None,
                                                                                            embedding_file_key='src_embedding_words_file',
                                                                                            embedding_file_with_header=False,
                                                                                            tokenizer=onmt.tokenizers.SpaceTokenizer(),
                                                                                            dropout=0.0),
                                                                               CharConvEmbedder(vocabulary_file_key="source_chars_vocabulary",
                                                                                               embedding_size=50,
                                                                                                num_outputs=100,
                                                                                                kernel_size=3,
                                                                                                stride=1,
                                                                                                dropout=0.3,
                                                                                                tokenizer=SpaceTokenizer())],
                                                                              reducer=ConcatReducer(),
                                                                              dropout=0.1),
                                                                WordEmbedder(vocabulary_file_key="feature_1_vocabulary",  # POS_TAG
                                                                             embedding_size=50,
                                                                             tokenizer=onmt.tokenizers.SpaceTokenizer(),
                                                                             trainable=True,
                                                                             dropout=0.2)
                                                                ],
                                                               reducer=ConcatReducer()),
                              target_inputter=WordEmbedder(vocabulary_file_key="target_words_vocabulary",
                                                           embedding_size=50,
                                                           trainable=True,
                                                           tokenizer=SpaceTokenizer(),
                                                           dropout=0.0),
                              encoder=ParallelEncoder([BidirectionalRNNEncoder(num_layers=2,
                                                                               num_units=256,
                                                                               cell_class=tf.contrib.rnn.LayerNormBasicLSTMCell,
                                                                               dropout=0.1),
                                                       SelfAttentionEncoder(num_layers=2,num_units=256)
                                                       ],
                                                      outputs_reducer=ConcatReducer(axis=1),
                                                      share_parameters=True),
                              decoder=onmt.decoders.RNMTPlusDecoder(num_layers=2,
                                                                          num_units=256,
                                                                          num_heads=8,
                                                                          cell_class=tf.contrib.rnn.LayerNormBasicLSTMCell,
                                                                          dropout=0.1))

```

Traceback (most recent call last):
  File "/mnt/shared/NaturalLanguageRecognition/NaturalLanguageManager/src/Server_Services/mlServiceTrainDispatcher.py", line 118, in <module>
    main()
  File "/mnt/shared/NaturalLanguageRecognition/NaturalLanguageManager/src/Server_Services/mlServiceTrainDispatcher.py", line 90, in main
    service.train(params=params)
  File "/mnt/shared/NaturalLanguageRecognition/NaturalLanguageManager/src/Service_Model/MLService.py", line 259, in train
    _train()
  File "/mnt/shared/NaturalLanguageRecognition/NaturalLanguageManager/src/Service_Model/MLService.py", line 226, in _train
    startTrain()
  File "/mnt/shared/NaturalLanguageRecognition/NaturalLanguageManager/src/Service_Model/MLService.py", line 172, in startTrain
    nnmtMain()
  File "/usr/local/lib/python3.6/dist-packages/opennmt/bin/main.py", line 161, in main
    runner.train_and_evaluate(checkpoint_path=args.checkpoint_path)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/runner.py", line 227, in train_and_evaluate
    tf.estimator.train_and_evaluate(self._estimator, train_spec, eval_spec)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/training.py", line 637, in run
    getattr(self, task_to_run)()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/training.py", line 647, in run_worker
    return self._start_distributed_training()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/training.py", line 788, in _start_distributed_training
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 1237, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/estimator/estimator.py", line 1195, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/models/model.py", line 123, in _model_fn
    _loss_op, features_shards, labels_shards, params, mode, config)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/utils/parallel.py", line 148, in __call__
    outputs.append(funs[i](*args[i], **kwargs[i]))
  File "/usr/local/lib/python3.6/dist-packages/opennmt/models/model.py", line 80, in _loss_op
    logits, _ = self._build(features, labels, params, mode, config=config)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/models/sequence_to_sequence.py", line 194, in _build
    mode=mode)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/encoders/encoder.py", line 162, in encode
    mode=mode)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/encoders/self_attention_encoder.py", line 70, in encode
    transformer.norm(inputs),
  File "/usr/local/lib/python3.6/dist-packages/opennmt/layers/transformer.py", line 321, in norm
    return tf.contrib.layers.layer_norm(inputs, begin_norm_axis=-1)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 2299, in layer_norm
    trainable=trainable)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 350, in model_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/contrib/framework/python/ops/variables.py", line 277, in variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1487, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 1237, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 540, in get_variable
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 492, in _true_getter
    aggregation=aggregation)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py", line 879, in _get_single_variable
    "reuse=tf.AUTO_REUSE in VarScope?" % name)
ValueError: Variable seq2seq/encoder/parallel_encoder/layer_0/multi_head/LayerNorm/beta does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=tf.AUTO_REUSE in VarScope?

**Comment by guillaumekln** [comment]
That's a very complex architecture. :)

I see that you set `share_parameters=True` to `ParallelEncoder` but the 2 encoders have very different parameters. You should remove this argument.

**Comment by lockder** [comment]
When we should use the shared parameters? I thought it was to share the same embedding with several encoders at the same time

Enviado desde mi iPhone

**Comment by guillaumekln** [comment]
The description of the argument is "If True, share parameters between the parallel encoders" so it means all parameters. This is commonly used for multi-source training.
