### ISSUE TITLE
NaN loss during training.

### ISSUE THREAD

**Issue by BigFishMaster** [OpenNMT/OpenNMT-tf#369]
I open this issue same as #156, with more details.

1. my running script:
```shell
$onmt_main train_and_eval \
          --model_type Transformer \
          --config ${root}/config/transformer.yml --auto_config \
          --num_gpus 4 \
          --data_dir ${root}
```
```python
# transformer.yml
model_dir: run

data:
    train_features_file: data/train_src.txt
    train_labels_file: data/train_tgt.txt
    eval_features_file: data/dev_src.txt
    eval_labels_file: data/dev_tgt.txt
    source_words_vocabulary: data/tokens.vocab
    target_words_vocabulary: data/tokens.vocab


params:
    average_loss_in_time: true
    label_smoothing: 0.1
    optimizer: LazyAdamOptimizer
    optimizer_params:
        beta1: 0.9
        beta2: 0.998
    learning_rate: 2.0
    decay_type: noam_decay_v2
    decay_params:
        model_dim: 512
        warmup_steps: 8000
    gradients_accum: 1
    beam_width: 4
    length_penalty: 0.6
    minimum_decoding_length: 0
    maximum_iterations: 200


train:
    effective_batch_size: null
    batch_size: 4096
    batch_type: tokens
    maximum_features_length: 50
    maximum_labels_length: 50
    sample_buffer_size: 0
    save_summary_steps: 100
    train_steps: 1000000
    keep_checkpoint_max: 8
    average_last_checkpoints: 8
    bucket_width: 8
    num_threads: 8
    prefetch_buffer_size: 4
    save_checkpoints_steps: 5000
    save_checkpoints_secs: null

eval:
    batch_size: 32
    num_threads: 1
    prefetch_buffer_size: 1
    external_evaluators: [BLEU, ROUGE]
    save_eval_predictions: true
    eval_delay: 1200
    exporter: last

infer:
    batch_size: 32
    bucket_width: 5
    num_threads: 1
    prefetch_buffer_size: 1
    n_best: 4
    with_scores: false

score:
    batch_size: 64
```

2. environment:
```
version: opennmt-tf v1.20.1
cuda: 9.0
gpu: P40 x 4
```
3. log info:
```python
INFO:tensorflow:loss = 4.168071, step = 92400 (43.831 sec)
INFO:tensorflow:source_words/sec: 21068
INFO:tensorflow:target_words/sec: 26083
ERROR:tensorflow:Model diverged with loss = NaN.
Traceback (most recent call last):
  File "/mnt/yardcephfs/mmyard/g_wxg_td_prc/chriscxyan/OpenNMT-TF/opennmt-tf/code/../OpenNMT-tf-1.20.1/opennmt/bin/main.py", line 205, in <module>
    main()
  File "/mnt/yardcephfs/mmyard/g_wxg_td_prc/chriscxyan/OpenNMT-TF/opennmt-tf/code/../OpenNMT-tf-1.20.1/opennmt/bin/main.py", line 174, in main
    runner.train_and_evaluate(checkpoint_path=args.checkpoint_path)
  File "/mnt/yardcephfs/mmyard/g_wxg_td_prc/chriscxyan/OpenNMT-TF/opennmt-tf/OpenNMT-tf-1.20.1/opennmt/runner.py", line 288, in train_and_evaluate
    result = tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/python3/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1320, in run
    run_metadata=run_metadata))
  File "/usr/local/python3/lib/python3.6/site-packages/tensorflow/python/training/basic_session_run_hooks.py", line 753, in after_run
    raise NanLossDuringTrainingError
tensorflow.python.training.basic_session_run_hooks.NanLossDuringTrainingError: NaN loss during training.

```

**Comment by guillaumekln** [comment]
The configuration file mostly looks good but I'm concerned by `sample_buffer_size: 0`. Why not shuffling the dataset? Depending on the data distribution, this could cause exploding gradients.

Can you also check in TensorBoard for the gradients norm, is there anything suspicious?

**Comment by BigFishMaster** [comment]
@guillaumekln below is my gradient norm:
![image](https://user-images.githubusercontent.com/4915869/53877979-977d4080-4045-11e9-9296-aae026bc84b5.png)

**Comment by guillaumekln** [comment]
Did you try with data shuffling?
