### ISSUE TITLE
"The graph couldn't be sorted in topological order" error when use gpu-build tensorflow serving

### ISSUE THREAD

**Issue by jacklone** [OpenNMT/OpenNMT-tf#37]
when I use tensorflow_model_server without gpu, it's ok. However, when using tensorflow_model_server build with gpu, it loads the model success, but error in processing the request.

tensorflow_model_server log:
```
2017-12-05 07:56:06.617010: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 375.66.0
2017-12-05 07:56:06.617028: I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 375.66.0
2017-12-05 07:56:06.682749: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:155] Restoring SavedModel bundle.

2017-12-05 07:56:07.306172: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:190] Running LegacyInitOp on SavedModel bundle.
2017-12-05 07:56:07.419016: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:284] Loading SavedModel: success. Took 845041 microseconds.
2017-12-05 07:56:07.419215: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: tech_90 version: 1512156186}
2017-12-05 07:56:07.422146: I tensorflow_serving/model_servers/main.cc:288] Running ModelServer at 0.0.0.0:50145 ...
2017-12-05 07:56:16.370747: E external/org_tensorflow/tensorflow/core/grappler/utils/topological_sort.cc:75] The graph couldn't be sorted in topological order.
```

client log:
```
2017-12-05 15:30:10 _server.py[line:381] ERROR Exception calling application: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="Incomplete graph, missing 1 inputs for seq2seq/decoder_1/decoder_1/GatherTree")
Traceback (most recent call last):
  File "/Users/xxx/anaconda/envs/py2/lib/python2.7/site-packages/grpc/_server.py", line 376, in _call_behavior
    return behavior(argument, context), True
  File "/Users/xxx/PycharmProjects/text-correction-rpc/src/diagnose_server.py", line 104, in doTextDiagnose
    src_words, tag_words, score = self.doctor.diagnose(check_sent)
  File "/Users/xxx/PycharmProjects/text-correction-rpc/src/core/doctor.py", line 99, in diagnose
    translate_res = translate_res.result()
  File "/Users/xxx/anaconda/envs/py2/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 97, in result
    raise _abortion_error(rpc_error_call)
AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="Incomplete graph, missing 1 inputs for seq2seq/decoder_1/decoder_1/GatherTree")
```

**Comment by guillaumekln** [comment]
Hello, did you solve it? What was the issue?

**Comment by jacklone** [comment]
@guillaumekln I think my docker image was wrongly built, I build it using the [official Dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu), all things seems ok, and mnist seving demo passed success, except this error.
Then I find this docker image,
https://hub.docker.com/r/sozercan/tensorflow-serving-devel-gpu/
this one is ok.
