### ISSUE TITLE
Error when exporting multi feature model

### ISSUE THREAD

**Issue by Dagamies** [OpenNMT/OpenNMT-tf#374]
There seems to be small issue with exporting a model having multiple input features:
Traceback (most recent call last):
  File "opennmt/bin/main.py", line 201, in <module>
    main()
  File "opennmt/bin/main.py", line 190, in main
    export_dir_base=args.export_dir_base)
  File "/home/ari/tf/Onmt-1211/OpenNMT-tf/opennmt/runner.py", line 456, in export
    _ = model.features_inputter.make_dataset(data_config["train_features_file"])
NameError: name 'model' is not defined

**Comment by guillaumekln** [comment]
Thanks for reporting.
