### ISSUE TITLE
AttributeError: '_VariantDataset' object has no attribute 'output_shapes'

### ISSUE THREAD

**Issue by sebastian-nehrdich** [OpenNMT/OpenNMT-tf#425]
This is related to https://github.com/OpenNMT/OpenNMT-tf/issues/398#issue-426757670, but since I am not using docker, but using the stable 1.13.1-release of TF, I think it is worth to open a new issue.
I get this  error on my setup. I have Ubuntu 18.04., Cuda 10.0, I built tensorflow from source with CUDA-support (version 1.13.1). I have the latest OpenNMT-tf installed via pip. I am quite puzzled, I already uninstalled the entire CUDA/tensorflow-complex, reinstalled it, I also tried cuda 10.1 (no improvement) and tensorflow 1.12.2 (fails for other reasons). Any suggestions on this?

```
Traceback (most recent call last):
  File "/usr/local/bin/onmt-main", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/opennmt/bin/main.py", line 172, in main
    runner.train_and_evaluate(checkpoint_path=args.checkpoint_path)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/runner.py", line 297, in train_and_evaluate
    result = tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 473, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 613, in run
    return self.run_local()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/training.py", line 714, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 367, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1158, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1185, in _train_model_default
    input_fn, ModeKeys.TRAIN))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1022, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1113, in _call_input_fn
    return input_fn(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/estimator.py", line 124, in _fn
    prefetch_buffer_size=prefetch_buffer_size)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/inputters/inputter.py", line 691, in make_training_dataset
    shard_index=shard_index)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/utils/data.py", line 311, in training_pipeline
    batch_size_multiple=batch_size_multiple))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1844, in apply
    return DatasetV1Adapter(super(DatasetV1, self).apply(transformation_func))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1271, in apply
    dataset = transformation_func(self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/experimental/ops/grouping.py", line 121, in _apply_fn
    window_size_func)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/experimental/ops/grouping.py", line 377, in __init__
    self._make_reduce_func(reduce_func, input_dataset)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/experimental/ops/grouping.py", line 424, in _make_reduce_func
    input_structure=input_structure)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2522, in __init__
    self._function = wrapper_fn._get_concrete_function_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1337, in _get_concrete_function_internal
    *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1331, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1594, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/function.py", line 1527, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py", line 713, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2516, in wrapper_fn
    ret = _wrapper_helper(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2456, in _wrapper_helper
    ret = func(*nested_args)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/utils/data.py", line 203, in _reduce_func
    return dataset.apply(batch_dataset(batch_size, padded_shapes=padded_shapes))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1271, in apply
    dataset = transformation_func(self)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/utils/data.py", line 143, in <lambda>
    batch_size, padded_shapes=padded_shapes or get_padded_shapes(dataset))
  File "/usr/local/lib/python3.6/dist-packages/opennmt/utils/data.py", line 22, in get_padded_shapes
    return compat.nest.map_structure(lambda shape: shape.as_list(), dataset.output_shapes)
AttributeError: '_VariantDataset' object has no attribute 'output_shapes'
```

This model used to work before, the error is only happening after I compiled tensorflow 1.13.1 from source. I can however not reconstruct with tf-version I was using before, I assume it installed during the summer of 2018.

**Comment by guillaumekln** [comment]
You probably did not build TensorFlow correctly, please check again. The reported lines in the stack trace do not match the TensorFlow code for the tag `v1.13.1`.

**Comment by sebastian-nehrdich** [comment]
Thank you very much! I think you are right, there seems to be something messed up with my installation of TF. I will try to sort this out - since it does not seem to be a problem on the side of OpenNMT-tf, I will close this.
