### ISSUE TITLE
Error with training SequenceTagger model

### ISSUE THREAD

**Issue by Goofy-G** [OpenNMT/OpenNMT-tf#430]
Hi
I occured one crash about vocabulary when I was using Seqtagger model to train.
The crash info:
/usr/local/lib/python3.5/dist-packages/opennmt/config.py:139: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  subconfig = yaml.load(config_file.read())
Traceback (most recent call last):
  File "/usr/local/bin/onmt-main", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/opennmt/bin/main.py", line 169, in main
    hvd=hvd)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/runner.py", line 96, in __init__
    self._model.initialize(self._config["data"])
  File "/usr/local/lib/python3.5/dist-packages/opennmt/models/sequence_tagger.py", line 54, in initialize
    super(SequenceTagger, self).initialize(metadata)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/models/model.py", line 70, in initialize
    self.examples_inputter.initialize(metadata)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/inputters/inputter.py", line 559, in initialize
    self.features_inputter.initialize(metadata, asset_prefix="source_")
  File "/usr/local/lib/python3.5/dist-packages/opennmt/inputters/inputter.py", line 313, in initialize
    inputter.initialize(metadata, asset_prefix="%s%d_" % (asset_prefix, i + 1))
  File "/usr/local/lib/python3.5/dist-packages/opennmt/inputters/text_inputter.py", line 356, in initialize
    metadata, asset_dir=asset_dir, asset_prefix=asset_prefix)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/inputters/text_inputter.py", line 251, in initialize
    self.vocabulary_file = metadata[self.vocabulary_file_key]
KeyError: 'words_vocabulary'
The parameters:
model_dir: /root/models/20190513/
data:
  train_features_file: /root/data/20190513/train.ocr
  train_labels_file: /root/data/20190513/train.std
  eval_features_file: /root/data/20190513/dev.ocr
  eval_labels_file: /root/data/20190513/dev.std
  source_words_vocabulary: /root/data/20190513/vocab_onmt.ocr
  target_words_vocabulary: /root/data/20190513/vocab_onmt.std
params:
  optimizer: GradientDescentOptimizer
  learning_rate: 1.0
  param_init: 0.1
  clip_gradients: 5.0
  decat_type: exponential_decay
  decay_rate: 0.7
  decay_steps: 50000
  start_decay_steps: 500000
  beam_width: 5
  maximum_iterations: 250
  replace_unknown_target: true

train:
  batch_size: 64
  bucket_width: 5
  save_checkpoints_steps: 10000
  save_summary_steps: 1000
  train_steps: 1000000
  maximum_features_length: 30
  maximum_labels_length: 30
  sample_buffer_size: -1

eval:
  batch_size: 32
  num_threads: 4
  eval_delay: 36000
  save_eval_predictions: true
  external_evaluations: BLEU
  exporters: last

infer:
  batch_size: 32
  num_threads: 1
  n_best: 1

**Comment by guillaumekln** [comment]
Hi,

See #337.

**Comment by Goofy-G** [comment]
Hi
So, how to set the parameters about word vocabulary

**Comment by Goofy-G** [comment]
Hi
  I have met one crash when using #337 model config.
Crash Info:
```
Caused by op 'cond/add_1', defined at:
  File "/usr/local/bin/onmt-main", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/opennmt/bin/main.py", line 172, in main
    runner.train_and_evaluate(checkpoint_path=args.checkpoint_path)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/runner.py", line 297, in train_and_evaluate
    result = tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 451, in train_and_evaluate
    return executor.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 590, in run
    return self.run_local()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/training.py", line 691, in run_local
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 376, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1145, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1170, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/estimator/estimator.py", line 1133, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/estimator.py", line 169, in _fn
    _loss_op, local_model, features_shards, labels_shards, params, mode)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/utils/parallel.py", line 151, in __call__
    outputs.append(funs[i](*args[i], **kwargs[i]))
  File "/usr/local/lib/python3.5/dist-packages/opennmt/estimator.py", line 239, in _loss_op
    return model.compute_loss(logits, labels, training=training, params=params)
  File "/usr/local/lib/python3.5/dist-packages/opennmt/models/sequence_tagger.py", line 108, in compute_loss
    transition_params=self.transition_params)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/crf/python/ops/crf.py", line 200, in crf_log_likelihood
    transition_params)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/crf/python/ops/crf.py", line 114, in crf_sequence_score
    false_fn=_multi_seq_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/layers/utils.py", line 206, in smart_cond
    pred, true_fn=true_fn, false_fn=false_fn, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/smart_cond.py", line 59, in smart_cond
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2057, in cond
    orig_res_f, res_f = context_f.BuildCondBranch(false_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1895, in BuildCondBranch
    original_result = fn()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/crf/python/ops/crf.py", line 104, in _multi_seq_fn
    unary_scores = crf_unary_score(tag_indices, sequence_lengths, inputs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/crf/python/ops/crf.py", line 230, in crf_unary_score
    flattened_tag_indices = array_ops.reshape(offsets + tag_indices, [-1])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/math_ops.py", line 850, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 297, in add
    "Add", x=x, y=y, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3155, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1717, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Incompatible shapes: [16,14] vs. [16,12]
	 [[Node: cond/add_1 = Add[T=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](cond/add, cond/add_1/Switch)]]
	 [[Node: cond_1/rnn/All/_389 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1698_cond_1/rnn/All", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]]
```
and  the hparameter
```
data:
  chars_vocabulary: /root/data/20190521/vocab.chars
  eval_features_file: /root/data/20190521/dev.ocr
  eval_labels_file: /root/data/20190521/dev.std
  tags_vocabulary: /root/data/20190521/vocab.tags
  train_features_file: /root/data/20190521/train.ocr
  train_labels_file: /root/data/20190521/train.std
  words_vocabulary: /root/data/20190521/vocab.words
eval:
  batch_size: 16
  eval_delay: 36000
  exporters: last
  external_evaluators: BLEU
  num_threads: 4
  save_eval_predictions: true
infer:
  batch_size: 16
  bucket_width: null
  n_best: 1
  num_threads: 1
model_dir: /root/models/20190521/
params:
  beam_width: 5
  clip_gradients: 5.0
  decat_type: exponential_decay
  decay_rate: 0.7
  decay_steps: 50000
  learning_rate: 1.0
  maximum_iterations: 250
  optimizer: GradientDescentOptimizer
  param_init: 0.1
  replace_unknown_target: true
  start_decay_steps: 500000
score:
  batch_size: 64
train:
  batch_size: 16
  batch_type: examples
  bucket_width: 5
  maximum_features_length: 30
  maximum_labels_length: 30
  sample_buffer_size: -1
  save_checkpoints_steps: 10000
  save_summary_steps: 1000
  train_steps: 1000000
```
