### ISSUE TITLE
Score not work in transformer

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/OpenNMT-tf#452]
when use the score function with transformer, got the following error. workaround is adding 1 more check in runner.py

      if "attention" in outputs and outputs["attention"] is not None:
        results["attention"] = outputs["attention"]

Traceback (most recent call last):
  File "/home/kawan/anaconda3/envs/zwy/bin/onmt-main", line 10, in <module>
    sys.exit(main())
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/opennmt/bin/main.py", line 197, in main
    checkpoint_path=args.checkpoint_path)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/opennmt/runner.py", line 539, in score
    tk = sess.run(results)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 930, in run
    run_metadata_ptr)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1138, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 472, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 264, in for_fetch
    return _DictFetchMapper(fetch)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 404, in __init__
    _FetchMapper.for_fetch(fetch) for fetch in fetches.values()
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 404, in <listcomp>
    _FetchMapper.for_fetch(fetch) for fetch in fetches.values()
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 264, in for_fetch
    return _DictFetchMapper(fetch)
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 404, in __init__
    _FetchMapper.for_fetch(fetch) for fetch in fetches.values()
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 404, in <listcomp>
    _FetchMapper.for_fetch(fetch) for fetch in fetches.values()
  File "/home/kawan/anaconda3/envs/zwy/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 259, in for_fetch
    type(fetch)))
TypeError: Fetch argument None has invalid type <class 'NoneType'>

**Comment by guillaumekln** [comment]
What is the configuration you are using?

**Comment by WangYongzhao** [comment]
command is 
CUDA_VISIBLE_DEVICES=0 onmt-main score --model_type Transformer  --auto_config  --config data_pure_transformer.yml --features_file  Q_test_char.tsv  --predictions_file  C_test_bpe.tsv

data_pure_transformer.yml  config is

model_dir: run/
data:
  train_features_file: Q_train_char.tsv
  train_labels_file: C_train_bpe.tsv
  eval_features_file: Q_test_char.tsv
  eval_labels_file: C_test_bpe.tsv
  source_words_vocabulary: src_vocab.txt
  target_words_vocabulary: tgt_vocab.txt

infer:
  n_best: 10
  with_scores: true
  with_alignments: null

**Comment by guillaumekln** [comment]
Are you using the latest OpenNMT-tf version?

**Comment by WangYongzhao** [comment]
no, what i use is 1.22.0, do you mean the issue will gone in latest version? I can give it a try

**Comment by guillaumekln** [comment]
I don't see how this value can be `None` given the configuration you shared above. Did you change the code?

**Comment by WangYongzhao** [comment]
the issue is gone in 1.23.0. I do change the code but not attention-related. 
close it for now.
