### ISSUE TITLE
using multi source transformer with guided alignments

### ISSUE THREAD

**Issue by kaleidoescape** [OpenNMT/OpenNMT-tf#460]
I'm trying to use the multi source transformer (https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/multi_source_transformer.py) for integrating both case features and alignments, but I'm running into a tensor shape problem. (Also, having said that, I'm not sure if the multi_source_transformer is the best way to do this.) 

For example, I have a BPEd (with sentencepiece) file such as train.src.bpe:

```
_hello _world !
```

And a parallel case_feats.txt file (with the same number of lines and tokens per line) such as:
```
C L N
```

On top of this, I would like to use an alignments file that I generated with fast_align.

My data configuration file looks like this:

```
data:
  eval_features_file: val.src.bpe
  eval_labels_file: val.tgt.bpe
  source_vocabulary_1: vocab.src.json
  source_vocabulary_2: case_feats.vocab
  target_vocabulary: vocab.tgt.json
  train_alignments: alignments.txt
  train_features_file:
  - train.src.bpe
  - case_feats.txt
  train_labels_file: train.tgt.bpe
```
Unfortunately, I'm getting the following error, and I'm not sure how best to debug it.

```
INFO:tensorflow:Not using Distribute Coordinator.
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after every checkpoint. Checkpoint frequency is determined based on RunConfig arguments: save_checkpoints_steps None or save_checkpoints_secs 600.
INFO:tensorflow:Training on 5997 examples
Traceback (most recent call last):
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1628, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes must be equal rank, but are 1 and 0
	From merging shape 0 with other shapes. for 'SparseTensor_5/dense_shape' (op: 'Pack') with input shapes: [2], [].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda/envs/onmt-tf/bin/onmt-main", line 11, in <module>
    load_entry_point('OpenNMT-tf', 'console_scripts', 'onmt-main')()
  File "/data/home/kaleidoescape/OpenNMT-tf/opennmt/bin/main.py", line 172, in main
    runner.train_and_evaluate(checkpoint_path=args.checkpoint_path)
  File "/data/home/kaleidoescape/OpenNMT-tf/opennmt/runner.py", line 301, in train_and_evaluate
    result = tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1234, in _train_model_default
    input_fn, model_fn_lib.ModeKeys.TRAIN))
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1075, in _get_features_and_labels_from_input_fn
    self._call_input_fn(input_fn, mode))
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1162, in _call_input_fn
    return input_fn(**kwargs)
  File "/data/home/kaleidoescape/OpenNMT-tf/opennmt/estimator.py", line 124, in _fn
    prefetch_buffer_size=prefetch_buffer_size)
  File "/data/home/kaleidoescape/OpenNMT-tf/opennmt/inputters/inputter.py", line 691, in make_training_dataset
    shard_index=shard_index)
  File "/data/home/kaleidoescape/OpenNMT-tf/opennmt/utils/data.py", line 302, in training_pipeline
    dataset = dataset.map(process_fn, num_parallel_calls=num_threads or 4)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1040, in map
    return ParallelMapDataset(self, map_func, num_parallel_calls)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2649, in __init__
    use_inter_op_parallelism)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2611, in __init__
    map_func, "Dataset.map()", input_dataset)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1860, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 479, in add_to_graph
    self._create_definition_if_needed()
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 335, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 344, in _create_definition_if_needed_impl
    self._capture_by_value, self._caller_device)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 864, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1794, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/data/home/kaleidoescape/OpenNMT-tf/opennmt/inputters/inputter.py", line 671, in <lambda>
    map_func = lambda *arg: self.make_features(arg, training=True)
  File "/data/home/kaleidoescape/OpenNMT-tf/opennmt/models/sequence_to_sequence.py", line 395, in make_features
    self.labels_inputter.get_length(labels) - 1)  # Ignore special token.
  File "/data/home/kaleidoescape/OpenNMT-tf/opennmt/models/sequence_to_sequence.py", line 437, in alignment_matrix_from_pharaoh
    sparse_indices, sparse_values, [source_length, target_length])
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/sparse_tensor.py", line 127, in __init__
    dense_shape, name="dense_shape", dtype=dtypes.int64)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1050, in convert_to_tensor
    as_ref=False)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1146, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 971, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 923, in _autopacking_helper
    return gen_array_ops.pack(elems_as_tensors, name=scope)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 4875, in pack
    "Pack", values=values, axis=axis, name=name)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/function.py", line 738, in create_op
    **kwargs)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1792, in __init__
    control_input_ops)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1631, in _create_c_op
    raise ValueError(str(e))
ValueError: Shapes must be equal rank, but are 1 and 0
	From merging shape 0 with other shapes. for 'SparseTensor_5/dense_shape' (op: 'Pack') with input shapes: [2], [].
```

First of all, does this approach make sense, or is there a better approach? If it does make sense, do you have some advice on how to best debug this error?

**Comment by WangYongzhao** [comment]
the issue should be missing 1 evaluation file, as you are using multi input

`eval_features_file: val.src.bpe`

you should follow train format

```
  train_features_file:
  - train.src.bpe
  - case_feats.txt
```

**Comment by guillaumekln** [comment]
You probably want to use the "multi features" concept and not "multi source". In multi source, the inputs are encoded separately and the decoder has separate attention layer for each. In multi features, the inputs embedding are simply concatenated. This is more appropriate for case features.

To do the latter, you just need to configure the `reducer` argument of the `ParallelInputter`, for example:

```python
import opennmt as onmt

class MultiFeaturesTransformer(onmt.models.Transformer):

  def __init__(self):
    super(MultiFeaturesTransformer, self).__init__(
      source_inputter=onmt.inputters.ParallelInputter([
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="source_vocabulary_1",
              embedding_size=448),
          onmt.inputters.WordEmbedder(
              vocabulary_file_key="source_vocabulary_2",
              embedding_size=64)],
          reducer=onmt.layers.ConcatReducer(axis=-1)),
      target_inputter=onmt.inputters.WordEmbedder(
          vocabulary_file_key="target_vocabulary",
          embedding_size=512),
      num_layers=6,
      num_units=512,
      num_heads=8,
      ffn_inner_dim=2048,
      dropout=0.1,
      attention_dropout=0.1,
      relu_dropout=0.1)

model = MultiFeaturesTransformer
```

**Comment by kaleidoescape** [comment]
Thank you both for the quick response. Yes, I think the multi features model makes more sense conceptually, and I updated my configuration to include the case features for the eval set as well, like so:

```
data:
  eval_features_file: 
  - val.src.bpe
  - case_feats.val
  eval_labels_file: val.tgt.bpe
  source_vocabulary_1: vocab.src.json
  source_vocabulary_2: case_feats.vocab
  target_vocabulary: vocab.tgt.json
  train_alignments: alignments.txt
  train_features_file:
  - train.src.bpe
  - case_feats.train
  train_labels_file: train.tgt.bpe
```

I also think this makes more sense now. However, I am still getting the following error:

```
Traceback (most recent call last):
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Indices are not valid (out of bounds).  Shape: [69,33]
	 [[{{node SparseToDense}} = SparseToDense[T=DT_FLOAT, Tindices=DT_INT64, validate_indices=false, _device="/device:CPU:0"](Reshape, SparseTensor_5/dense_shape, ones, SparseToDense/default_value)]]
	 [[{{node IteratorGetNext}} = IteratorGetNext[output_shapes=[[?,?], [?], [?,?], [?,?], [?], [?,?], [?,?,?], [?,?], [?,?], [?], [?,?]], output_types=[DT_INT64, DT_INT32, DT_STRING, DT_INT64, DT_INT32, DT_STRING, DT_FLOAT, DT_INT64, DT_INT64, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/anaconda/envs/onmt-tf/bin/onmt-main", line 11, in <module>
    load_entry_point('OpenNMT-tf', 'console_scripts', 'onmt-main')()
  File "/data/home/kaleidoescape/OpenNMT-tf/opennmt/bin/main.py", line 172, in main
    runner.train_and_evaluate(checkpoint_path=args.checkpoint_path)
  File "/data/home/kaleidoescape/OpenNMT-tf/opennmt/runner.py", line 301, in train_and_evaluate
    result = tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 471, in train_and_evaluate
    return executor.run()
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 610, in run
    return self.run_local()
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/training.py", line 711, in run_local
    saving_listeners=saving_listeners)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1241, in _train_model_default
    saving_listeners)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1471, in _train_with_estimator_spec
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 671, in run
    run_metadata=run_metadata)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1156, in run
    run_metadata=run_metadata)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1255, in run
    raise six.reraise(*original_exc_info)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1240, in run
    return self._sess.run(*args, **kwargs)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1312, in run
    run_metadata=run_metadata)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1076, in run
    return self._sess.run(*args, **kwargs)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/data/anaconda/envs/onmt-tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Indices are not valid (out of bounds).  Shape: [69,33]
	 [[{{node SparseToDense}} = SparseToDense[T=DT_FLOAT, Tindices=DT_INT64, validate_indices=false, _device="/device:CPU:0"](Reshape, SparseTensor_5/dense_shape, ones, SparseToDense/default_value)]]
	 [[node IteratorGetNext (defined at /data/home/kaleidoescape/OpenNMT-tf/opennmt/estimator.py:132)  = IteratorGetNext[output_shapes=[[?,?], [?], [?,?], [?,?], [?], [?,?], [?,?,?], [?,?], [?,?], [?], [?,?]], output_types=[DT_INT64, DT_INT32, DT_STRING, DT_INT64, DT_INT32, DT_STRING, DT_FLOAT, DT_INT64, DT_INT64, DT_INT32, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](IteratorV2)]]
```

Is it possible the problem is coming from some mismatched lines in the data set?

In addition, I'm still not sure of the best way to debug these sorts of problems. For example, do you know if there is a nice way in OpenNMT-tf that I can inspect tensors? I am new to TF, and although I have read about some ways that I can use the tf debugger or tf.print, I am still having trouble understanding how to properly invoke either of them, with respect to the rest of the OpenNMT-tf structure.

**Comment by guillaumekln** [comment]
Most likely your alignment file is incorrect or not aligned with your training data. You might want to check that for each example, the alignment indices are not out of bounds. I think it's easier to debug this outside of the TensorFlow code.

**Comment by kaleidoescape** [comment]
It's true, there was a problem in the alignments! Thank you very much for your help!

As a general question though, is there a nice or typical way of debugging in OpenNMT-tf?

**Comment by guillaumekln** [comment]
If I really need to inspect Tensor values, I usually just go with [`tf.Print`](https://www.tensorflow.org/api_docs/python/tf/Print).

**Comment by mohammedayub44** [comment]
@kaleidoescape @guillaumekln  How you detect the issues in the Alignment file, any particular script you used or manual process. I think I'm running into the same error on my file. Any suggestions would be helpful.

Thanks.

**Comment by kaleidoescape** [comment]
@mohammedayub44 In the end, I didn't have a very clever method. I just wrote something to report if an alignment index was out of bounds of the length of my tokens on a given line, and eventually found the one data set that had been incorrectly passed in in one portion of the rest of my pipeline, which caused this mismatch.

**Comment by mohammedayub44** [comment]
Oh okay. Thanks. I also realized that for fine tuning you don't really need the alignments file for your domain dataset. The generated base model's attentions (using alignment file only for base model)  get tuned directly by just updating the vocabulary and updated checkpoint.
