### ISSUE TITLE
(branch: v2) evaluation bug. (in training phrase)

### ISSUE THREAD

**Issue by nilbibi** [OpenNMT/OpenNMT-tf#491]
when I run scripts/wmt/run_wmt_ende_1gpu.sh, I found this error in the second evaluation.
>Traceback (most recent call last):
  File "/home/xinghua/miniconda3/envs/tf2.0/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/xinghua/miniconda3/envs/tf2.0/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/xinghua/nb_project/OpenNMT-tf/opennmt/bin/main.py", line 221, in <module>
    main()
  File "/data/xinghua/nb_project/OpenNMT-tf/opennmt/bin/main.py", line 187, in main
    checkpoint_path=args.checkpoint_path)
  File "/data/xinghua/nb_project/OpenNMT-tf/opennmt/runner.py", line 204, in train
    eval_steps=eval_config.get("steps", 5000))
  File "/data/xinghua/nb_project/OpenNMT-tf/opennmt/training.py", line 159, in __call__
    evaluator(step)
  File "/data/xinghua/nb_project/OpenNMT-tf/opennmt/evaluation.py", line 142, in __call__
    loss = loss_num / loss_den
ZeroDivisionError: division by zero

I tracked to the following code.
```
 iterator = iter(dataset)

  def decorator(func):

    @tf.function
    def _tf_fun():
      return func(lambda: next(iterator))

    def _fun():
      while True:
        try:
          yield _tf_fun()
        except tf.errors.OutOfRangeError:
          break

    return _fun
```
I change the code as below, Is this change appropriate?
```
def decorator(func):
    def _fun():
      iterator = iter(dataset)
      @tf.function
      def _tf_fun():
        return func(lambda: next(iterator))

      while True:
        try:
          yield _tf_fun()
        except tf.errors.OutOfRangeError:
          break

    return _fun
```

**Comment by guillaumekln** [comment]
Thanks for testing this branch. I'm not sure your change is related to the error. Do you have an empty line in your validation set?

**Comment by nilbibi** [comment]
There is no empty line in validation set, I guess the iterator is out of range when the second evaluation.(The first time evaluation has run out of elements in dataset), so the next time evaluation need to reset the iterator.

**Comment by guillaumekln** [comment]
Ah, good catch! The change looks appropriate, I will do additional tests. Thanks!

**Comment by guillaumekln** [comment]
I applied your change in the commit above. Thanks!
