### ISSUE TITLE
Tagger with CRF fails on sequences of length 1

### ISSUE THREAD

**Issue by WangYongzhao** [OpenNMT/OpenNMT-tf#547]
```
File "/opt/anaconda3/bin/onmt-main", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 189, in main
    checkpoint_path=args.checkpoint_path)
  File "/opt/anaconda3/lib/python3.7/site-packages/opennmt/runner.py", line 187, in train
    mixed_precision=self._mixed_precision)
  File "/opt/anaconda3/lib/python3.7/site-packages/opennmt/training.py", line 27, in __init__
    raise ValueError("No optimizer is defined")
ValueError: No optimizer is defined
```

my command is:  onmt-main  --config tag22.yml --model_type LstmCnnCrfTagger train
and with OpenNMT-tf 2.2.1

tag22.yml

```
model_dir: tag4/
data:
  train_features_file: tag_train_q.txt
  train_labels_file:  tag_train_l.txt
  eval_features_file: tag_test_q.txt
  eval_labels_file: tag_test_l.txt
  source_1_vocabulary: tag_src.txt
  source_2_vocabulary: char_vocab.txt
  target_vocabulary: tag.txt
train:
  batch_size: 32
  effective_batch_size: 320
  sample_buffer_size: 10000000
  bucket_width: 5
  train_steps: 1000000000

infer:
  n_best: 30
  batch_size: 1
  with_scores: false
  with_alignments: null

```

**Comment by guillaumekln** [comment]
You should define an optimizer in your configuration, e.g.:

```yaml
params:
  optimizer: Adam
  learning_rate: 0.001
```

**Comment by WangYongzhao** [comment]
after enable this, and got new error

````
tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: Tried to stack elements of an empty list with non-fully-defined element_shape: [?,2]
         [[{{node cond_2/then/_35/scan/TensorArrayV2Stack/TensorListStack}}]]
Traceback (most recent call last):
  File "/opt/anaconda3/bin/onmt-main", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 189, in main
    checkpoint_path=args.checkpoint_path)
  File "/opt/anaconda3/lib/python3.7/site-packages/opennmt/runner.py", line 196, in train
    export_on_best=eval_config.get("export_on_best"))
  File "/opt/anaconda3/lib/python3.7/site-packages/opennmt/training.py", line 175, in __call__
    for i, (loss, num_words, skipped) in enumerate(_forward()):  # pylint: disable=no-value-for-parameter
  File "/opt/anaconda3/lib/python3.7/site-packages/opennmt/data/dataset.py", line 433, in _fun
    outputs = _tf_fun()
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 487, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Tried to stack elements of an empty list with non-fully-defined element_shape: [?,2]
         [[{{node cond_2/then/_35/scan/TensorArrayV2Stack/TensorListStack}}]] [Op:__inference__tf_fun_8432]

Function call stack:
_tf_fun
```

**Comment by WangYongzhao** [comment]
BTW, should be super(LstmCnnCrfTagger .....

https://github.com/OpenNMT/OpenNMT-tf/blob/master/opennmt/models/catalog.py#L125

**Comment by guillaumekln** [comment]
> after enable this, and got new error

Thanks, I was able to reproduce. I will have a look.

> BTW, should be super(LstmCnnCrfTagger .....

This one is fixed by the PR linked above.

**Comment by guillaumekln** [comment]
The error is ine the CRF module from TensorFlow Addons. I opened an issue there: https://github.com/tensorflow/addons/issues/694.

In the meantime, you could disable `crf_decoding`.

**Comment by guillaumekln** [comment]
Let's keep this open to track when the fix will be included in OpenNMT-tf.

**Comment by Squadrick** [comment]
Fixed in TFA by commit  https://github.com/tensorflow/addons/commit/7f68da6c717c232bc0760ca1ab9ad13ce26f221a

**Comment by guillaumekln** [comment]
Thanks for the fix @Squadrick!
