### ISSUE TITLE
Unable to use GPU

### ISSUE THREAD

**Issue by mdasadul** [OpenNMT/OpenNMT-tf#629]
I have been trying to use opennmt-tf and I am getting following errors. Given that I have been using this before and working as expected but after updating the repo seems GPU is not visible 

CUDA_VISIBLE_DEVICES=0,1,2,3 onmt-main --model_type Transformer --config data.yml --auto_config train --with_eval --num_gpus=4

ed in a future version.
Instructions for updating:
Use eager execution and:
`tf.data.TFRecordDataset(path)`
INFO:tensorflow:Accumulate gradients of 3 iterations to reach effective batch size of 25000
Traceback (most recent call last):
  File "/data/asadul/research/opennmt-tf/venv/bin/onmt-main", line 8, in <module>
    sys.exit(main())
  File "/data/asadul/research/opennmt-tf/venv/lib/python3.6/site-packages/opennmt/bin/main.py", line 204, in main
    checkpoint_path=args.checkpoint_path)
  File "/data/asadul/research/opennmt-tf/venv/lib/python3.6/site-packages/opennmt/runner.py", line 199, in train
    devices=misc.get_devices(count=num_devices))
  File "/data/asadul/research/opennmt-tf/venv/lib/python3.6/site-packages/opennmt/utils/misc.py", line 33, in get_devices
    raise ValueError("Requested %d devices but only %d are visible" % (count, len(devices)))
ValueError: Requested 4 devices but only 1 are visible

**Comment by guillaumekln** [comment]
Most likely you updated from a version that is older than 2.5. Since 2.5, OpenNMT-tf uses TensorFlow 2.1 which requires CUDA 10.1. If this CUDA version is not found on the system, the code will fallback to use the CPU only.

Can you check that you have CUDA 10.1 installed? Also see the [TensorFlow documentation](https://www.tensorflow.org/install/gpu) about GPU support.

**Comment by guillaumekln** [comment]
@mdasadul Any update on this?

**Comment by islamalh** [comment]
I reinstall nvidia-drivers and OpenNMT-tf. After that it's working as expected

'

**Comment by FPBHW** [comment]
Hi,

we encounter a similar problem. We upgraded to OpenNMT version v2.20.0 due to tokenization issues. Currently, we see:
```
2021-06-30 22:07:29.427086: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

2021-06-30 22:07:29.427112: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10

2021-06-30 22:07:29.427123: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10

2021-06-30 22:07:29.427133: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10

2021-06-30 22:07:29.427143: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10

2021-06-30 22:07:29.427152: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10

2021-06-30 22:07:29.427162: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7

2021-06-30 22:07:29.450581: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7

2021-06-30 22:07:29.450625: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

2021-06-30 22:07:34.768925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1257] Device interconnect StreamExecutor with strength 1 edge matrix:

2021-06-30 22:07:34.768979: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1263]      0 1 2 3 4 5 6 7 

2021-06-30 22:07:34.768990: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 0:   N Y Y Y Y Y Y Y 

2021-06-30 22:07:34.768997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 1:   Y N Y Y Y Y Y Y 

2021-06-30 22:07:34.769003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 2:   Y Y N Y Y Y Y Y 

2021-06-30 22:07:34.769010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 3:   Y Y Y N Y Y Y Y 

2021-06-30 22:07:34.769016: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 4:   Y Y Y Y N Y Y Y 

2021-06-30 22:07:34.769023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 5:   Y Y Y Y Y N Y Y 

2021-06-30 22:07:34.769029: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 6:   Y Y Y Y Y Y N Y 

2021-06-30 22:07:34.769035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1276] 7:   Y Y Y Y Y Y Y N 

2021-06-30 22:07:34.784618: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30120 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:2d:00.0, compute capability: 7.0)

2021-06-30 22:07:34.786520: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30120 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-32GB, pci bus id: 0000:32:00.0, compute capability: 7.0)

2021-06-30 22:07:34.788286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 30120 MB memory) -> physical GPU (device: 2, name: Tesla V100-SXM2-32GB, pci bus id: 0000:5b:00.0, compute capability: 7.0)

2021-06-30 22:07:34.790445: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 30120 MB memory) -> physical GPU (device: 3, name: Tesla V100-SXM2-32GB, pci bus id: 0000:5f:00.0, compute capability: 7.0)

2021-06-30 22:07:34.792601: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 30120 MB memory) -> physical GPU (device: 4, name: Tesla V100-SXM2-32GB, pci bus id: 0000:b5:00.0, compute capability: 7.0)

2021-06-30 22:07:34.794338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 30120 MB memory) -> physical GPU (device: 5, name: Tesla V100-SXM2-32GB, pci bus id: 0000:be:00.0, compute capability: 7.0)

2021-06-30 22:07:34.796542: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:6 with 30120 MB memory) -> physical GPU (device: 6, name: Tesla V100-SXM2-32GB, pci bus id: 0000:e1:00.0, compute capability: 7.0)

2021-06-30 22:07:34.798292: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1402] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 30120 MB memory) -> physical GPU (device: 7, name: Tesla V100-SXM2-32GB, pci bus id: 0000:e9:00.0, compute capability: 7.0)

2021-06-30 22:07:34.807000: I main.py:326] Searching the largest batch size between 256 and 16384 with a precision of 256...

2021-06-30 22:07:34.812000: I main.py:326] Trying training with batch size 8320...

2021-06-30 22:07:36.669000: I main.py:326] ... failed.

2021-06-30 22:07:36.673000: I main.py:326] Trying training with batch size 4287...

2021-06-30 22:07:38.471000: I main.py:326] ... failed.

2021-06-30 22:07:38.476000: I main.py:326] Trying training with batch size 2271...

2021-06-30 22:07:40.358000: I main.py:326] ... failed.

2021-06-30 22:07:40.362000: I main.py:326] Trying training with batch size 1263...

2021-06-30 22:07:42.132000: I main.py:326] ... failed.

2021-06-30 22:07:42.137000: I main.py:326] Trying training with batch size 759...

2021-06-30 22:07:43.933000: I main.py:326] ... failed.

2021-06-30 22:07:43.938000: I main.py:326] Trying training with batch size 507...

2021-06-30 22:07:45.715000: I main.py:326] ... failed.

2021-06-30 22:07:45.715000: E main.py:326] Last training attempt exited with an error:

"""

Traceback (most recent call last):

  File "/root/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/root/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 363, in <module>

    main()

  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 326, in main

    hvd=hvd,

  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/runner.py", line 196, in train

    devices = misc.get_devices(count=num_devices, fallback_to_cpu=fallback_to_cpu)

  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/utils/misc.py", line 47, in get_devices

    "is" if len(devices) == 1 else "are",

ValueError: Requested 8 CPU devices but 1 CPU is visible

```

**Comment by FPBHW** [comment]
We have tried both tensorflow 2.3 + cuda10.1 and TF 2.4 + CUDA 11

**Comment by guillaumekln** [comment]
Hi,

Can you post the command line that you are running?

**Comment by FPBHW** [comment]
Thought it would be better to open a new issue, see #847  Will post there.
