### ISSUE TITLE
latest code error: Tensor conversion requested dtype float32 for Tensor with dtype int32

### ISSUE THREAD

**Issue by alucardpj** [OpenNMT/OpenNMT-tf#63]
when I use the latest commit  0f43259 to train my model, I got these error messages

> 2018-02-08 16:06:31.254817: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2018-02-08 16:06:32.060998: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-02-08 16:06:32.061448: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties: 
name: GeForce GTX 980 Ti major: 5 minor: 2 memoryClockRate(GHz): 1.114
pciBusID: 0000:04:00.0
totalMemory: 5.93GiB freeMemory: 5.83GiB
2018-02-08 16:06:32.061477: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:04:00.0, compute capability: 5.2)
INFO:tensorflow:Using config: {'_task_type': 'worker', '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fa23ba12208>, '_tf_random_seed': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_save_summary_steps': 50, '_save_checkpoints_steps': 1000, '_num_worker_replicas': 1, '_is_chief': True, '_save_checkpoints_secs': None, '_session_config': gpu_options {
}
allow_soft_placement: true
, '_task_id': 0, '_num_ps_replicas': 0, '_service': None, '_log_step_count_steps': 50, '_model_dir': 'models/seq-tagging-020816', '_master': ''}
INFO:tensorflow:Running training and evaluation locally (non-distributed).
INFO:tensorflow:Start train and evaluate loop. The evaluate will happen after 300 secs (eval_spec.throttle_secs) or training is finished.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ssdDisk/code/opennmt-tf-0110/bin/main.py", line 335, in <module>
    main()
  File "/ssdDisk/code/opennmt-tf-0110/bin/main.py", line 317, in main
    train(estimator, model, config, num_devices=args.num_gpus)
  File "/ssdDisk/code/opennmt-tf-0110/bin/main.py", line 153, in train
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/workHome/venv/py3-tf15/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 432, in train_and_evaluate
    executor.run_local()
  File "/workHome/venv/py3-tf15/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 611, in run_local
    hooks=train_hooks)
  File "/workHome/venv/py3-tf15/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/workHome/venv/py3-tf15/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 743, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/workHome/venv/py3-tf15/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/ssdDisk/code/opennmt-tf-0110/opennmt/models/model.py", line 78, in _model_fn
    loss = _extract_loss(losses_shards)
  File "/ssdDisk/code/opennmt-tf-0110/opennmt/models/model.py", line 61, in _extract_loss
    actual_loss = _normalize_loss(loss[0], den=loss[1])
  File "/ssdDisk/code/opennmt-tf-0110/opennmt/models/model.py", line 47, in _normalize_loss
    return tf.add_n(num) / tf.add_n(den)
  File "/workHome/venv/py3-tf15/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 898, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/workHome/venv/py3-tf15/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 932, in convert_to_tensor
    as_ref=False)
  File "/workHome/venv/py3-tf15/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1022, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/workHome/venv/py3-tf15/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 866, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 'Tensor("seqtagger/parallel_0/seqtagger/strided_slice:0", shape=(), dtype=int32, device=/device:GPU:0)'

but if I reset the commit to cb66148199d33cb7087d0da297590681514faf6d, everything is OK.
Is there something wrong during the two commits?

**Comment by guillaumekln** [comment]
Thank you for reporting. The commit above fixes this error.

**Comment by alucardpj** [comment]
the same error also happened in sequence_classifier.

> Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/hgfs/vdata/OpenNMT-tf/bin/main.py", line 335, in <module>
    main()
  File "/mnt/hgfs/vdata/OpenNMT-tf/bin/main.py", line 317, in main
    train(estimator, model, config, num_devices=args.num_gpus)
  File "/mnt/hgfs/vdata/OpenNMT-tf/bin/main.py", line 153, in train
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
  File "/home/pengjian/venv/py3/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 432, in train_and_evaluate
    executor.run_local()
  File "/home/pengjian/venv/py3/lib/python3.5/site-packages/tensorflow/python/estimator/training.py", line 611, in run_local
    hooks=train_hooks)
  File "/home/pengjian/venv/py3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 314, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/pengjian/venv/py3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 743, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/pengjian/venv/py3/lib/python3.5/site-packages/tensorflow/python/estimator/estimator.py", line 725, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/mnt/hgfs/vdata/OpenNMT-tf/opennmt/models/model.py", line 78, in _model_fn
    loss = _extract_loss(losses_shards)
  File "/mnt/hgfs/vdata/OpenNMT-tf/opennmt/models/model.py", line 61, in _extract_loss
    actual_loss = _normalize_loss(loss[0], den=loss[1])
  File "/mnt/hgfs/vdata/OpenNMT-tf/opennmt/models/model.py", line 47, in _normalize_loss
    return tf.add_n(num) / tf.add_n(den)
  File "/home/pengjian/venv/py3/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py", line 898, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
  File "/home/pengjian/venv/py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 932, in convert_to_tensor
    as_ref=False)
  File "/home/pengjian/venv/py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1022, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/pengjian/venv/py3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 866, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int32: 'Tensor("seqclassifier/parallel_0/seqclassifier/strided_slice:0", shape=(), dtype=int32)'

**Comment by guillaumekln** [comment]
Oh right. Thank you for testing these model variants!
