### ISSUE TITLE
PRF evaluator: list index out of range

### ISSUE THREAD

**Issue by dmit25** [OpenNMT/OpenNMT-tf#655]
Hi! 
I'm getting `list index out of range` when prf evaluator is used.

**Config:**
Model: TransformerRelative
params:
  beam_width: 1

train:
  maximum_features_length: 50
  maximum_labels_length: 50
  save_summary_steps: 100
  sample_buffer_size: 1000000
  keep_checkpoint_max: 20
  save_checkpoints_steps: 5000
  max_step: 2000000

eval:
  batch_size: 32
  steps: 5000
  export_on_best: bleu
  external_evaluators: [ "bleu", "prf", "wer" ]

infer:
  batch_size: 1024

**Full stack:**
W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
Traceback (most recent call last):
  File "/home/dima/anaconda3/envs/tf/bin/onmt-main", line 8, in <module>
    sys.exit(main())
  File "/home/dima/anaconda3/envs/tf/lib/python3.7/site-packages/opennmt/bin/main.py", line 224, in main
    hvd=hvd)
  File "/home/dima/anaconda3/envs/tf/lib/python3.7/site-packages/opennmt/runner.py", line 217, in train
    moving_average_decay=train_config.get("moving_average_decay"))
  File "/home/dima/anaconda3/envs/tf/lib/python3.7/site-packages/opennmt/training.py", line 118, in __call__
    early_stop = self._evaluate(evaluator, step, moving_average=moving_average)
  File "/home/dima/anaconda3/envs/tf/lib/python3.7/site-packages/opennmt/training.py", line 140, in _evaluate
    evaluator(step)
  File "/home/dima/anaconda3/envs/tf/lib/python3.7/site-packages/opennmt/evaluation.py", line 299, in __call__
    score = scorer(self._labels_file, output_path)
  File "/home/dima/anaconda3/envs/tf/lib/python3.7/site-packages/opennmt/utils/scorers.py", line 132, in __call__
    precision_score, recall_score, fmeasure_score = fmeasure(ref_path, hyp_path)
  File "/home/dima/anaconda3/envs/tf/lib/python3.7/site-packages/opennmt/utils/fmeasure.py", line 49, in fmeasure
    if tag == classref[linecpt][tagcpt]:
IndexError: list index out of range

Can I help you with  the issue? I'm not familiar with the code base, but I can try to reproduce it locally and extract the context if necessary.

**Comment by guillaumekln** [comment]
Hello,

@cservan Does the error mean anything to you?

> Can I help you with the issue? I'm not familiar with the code base, but I can try to reproduce it locally and extract the context if necessary.

Sure, that would be helpful. If you want to go further and fix the issue, you could first try to add a test in `opennmt/tests/scorers_test.py` to reproduce the error. (You can fin more information on how to run tests [here](https://github.com/OpenNMT/OpenNMT-tf/blob/master/CONTRIBUTING.md#testing).)

**Comment by cservan** [comment]
Thanks @guillaumekln ,
I'll take a look, it seems it comes from the "prf" scorer.
Cheers,
C.

**Comment by guillaumekln** [comment]
It is most likely related to an empty hypothesis or reference.
