### ISSUE TITLE
Multiple vocab

### ISSUE THREAD

**Issue by xustev75** [OpenNMT/OpenNMT-tf#739]
Document provided example in the case of multiple sources and vocab files:

data:
  source_1_vocabulary: src_1_vocab.txt  # Vocabulary of the 1st source input.
  source_2_vocabulary: src_2_vocab.txt  # Vocabulary of the 2nd source input.

but it returns the error message of:
KeyError: "Missing field 'source_vocabulary' in the data configuration"

**Comment by xustev75** [comment]
Here is the whole stack trace:
Traceback (most recent call last):
  File "/home/tingdong/.local/bin/onmt-main", line 8, in <module>
    sys.exit(main())
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/bin/main.py", line 227, in main
    runner.train(
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/runner.py", line 173, in train
    model = self._init_model(config)
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/runner.py", line 140, in _init_model
    model.initialize(config["data"], params=config["params"])
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/models/sequence_to_sequence.py", line 130, in initialize
    super(SequenceToSequence, self).initialize(data_config, params=params)
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/models/model.py", line 74, in initialize
    self.examples_inputter.initialize(data_config)
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/models/sequence_to_sequence.py", line 429, in initialize
    super(SequenceToSequenceInputter, self).initialize(data_config)
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/inputters/inputter.py", line 277, in initialize
    inputter.initialize(misc.RelativeConfig(
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/inputters/text_inputter.py", line 360, in initialize
    super(WordEmbedder, self).initialize(data_config)
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/inputters/text_inputter.py", line 220, in initialize
    self.vocabulary_file = data_config["vocabulary"]
  File "/home/tingdong/.local/lib/python3.8/site-packages/opennmt/utils/misc.py", line 478, in __getitem__
    raise KeyError("Missing field '%s' in the %sconfiguration" % (
KeyError: "Missing field 'source_vocabulary' in the data configuration"

**Comment by guillaumekln** [comment]
What model definition are you using?

Here is an example definition for a model using multiple sources and vocabularies: https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/multi_source_transformer.py

**Comment by xustev75** [comment]
I am using Transformer. 

So by your example, I will need to create my own custom model? I thought this is build-in function. It didn't give me any trouble with the source and target. Only error was from vocab file.

https://opennmt.net/OpenNMT-tf/vocabulary.html

**Comment by guillaumekln** [comment]
You need to use [this model definition](https://github.com/OpenNMT/OpenNMT-tf/blob/master/config/models/multi_source_transformer.py) to train a multi source Transformer model: . Once you downloaded the file, it can be used with:

```
onmt-main --model multi_source_transformer.py [...]
```

More information about custom models [here](https://opennmt.net/OpenNMT-tf/model.html#custom-models).

**Comment by xustev75** [comment]
how do you capture multiple targets and weights? Thanks

**Comment by guillaumekln** [comment]
What do you mean? Multiple targets are not supported.

**Comment by xustev75** [comment]
[(https://opennmt.net/OpenNMT-tf/data.html)]
`
data:
  train_features_file:
    - domain_a.en
    - domain_b.en
    - domain_c.en
  train_labels_file:
    - domain_a.de
    - domain_b.de
    - domain_c.de
  train_files_weights:
    - 0.5
    - 0.2
    - 0.3
`

**Comment by guillaumekln** [comment]
This is unrelated to the initial issue. Please open a new issue if you find a bug or post on the [forum](https://forum.opennmt.net/) for support.
