### ISSUE TITLE
RuntimeError: Model diverged with loss = NaN. 

### ISSUE THREAD

**Issue by ishaansharma** [OpenNMT/OpenNMT-tf#744]
I am trying to train a model using GPT2Small . And I am using OpenNMT version '2.13.0'

I got the following error while training : 
```
INFO:tensorflow:Saved checkpoint data/model_gpt/ckpt-435000
INFO:tensorflow:Running evaluation for step 435000
INFO:tensorflow:Evaluation result for step 435000: loss = 148890.718750 ; perplexity = inf
INFO:tensorflow:Step = 435100 ; steps/s = 2.97, source words/s = 12176 ; Learning rate = 1.202480 ; Loss = 185912.781250
INFO:tensorflow:Step = 435200 ; steps/s = 2.93, source words/s = 12020 ; Learning rate = 1.202172 ; Loss = 158771.156250
INFO:tensorflow:Step = 435300 ; steps/s = 2.95, source words/s = 12102 ; Learning rate = 1.201864 ; Loss = 138000.156250
INFO:tensorflow:Step = 435400 ; steps/s = 2.96, source words/s = 12106 ; Learning rate = 1.201557 ; Loss = 159760.921875
INFO:tensorflow:Step = 435500 ; steps/s = 2.95, source words/s = 12101 ; Learning rate = 1.201249 ; Loss = 159738.687500
INFO:tensorflow:Step = 435600 ; steps/s = 2.96, source words/s = 12111 ; Learning rate = 1.200941 ; Loss = 169730.593750
INFO:tensorflow:Step = 435700 ; steps/s = 2.96, source words/s = 12105 ; Learning rate = 1.200633 ; Loss = 141221.359375
INFO:tensorflow:Step = 435800 ; steps/s = 2.95, source words/s = 12103 ; Learning rate = 1.200325 ; Loss = 161559.109375
INFO:tensorflow:Step = 435900 ; steps/s = 2.95, source words/s = 12082 ; Learning rate = 1.200018 ; Loss = 172444.093750
INFO:tensorflow:Step = 436000 ; steps/s = 2.96, source words/s = 12105 ; Learning rate = 1.199710 ; Loss = 168357.078125
INFO:tensorflow:Step = 436100 ; steps/s = 2.89, source words/s = 11789 ; Learning rate = 1.199402 ; Loss = 154027.578125
INFO:tensorflow:Step = 436200 ; steps/s = 2.95, source words/s = 12083 ; Learning rate = 1.199094 ; Loss = 183578.703125
Traceback (most recent call last):
  File "train-gpt2.py", line 184, in <module>

  File "train-gpt2.py", line 180, in main

  File "/opt/conda/lib/python3.8/site-packages/opennmt/runner.py", line 237, in train
    summary = trainer(
  File "/opt/conda/lib/python3.8/site-packages/opennmt/training.py", line 99, in __call__
    raise RuntimeError("Model diverged with loss = NaN.")
RuntimeError: Model diverged with loss = NaN.
```
Below you can find my code which I used to train the model. 

```
import tensorflow as tf
import tensorflow_addons as tfa

from opennmt import decoders
from opennmt import encoders
from opennmt import inputters
from opennmt import layers
from opennmt.models import language_model
from opennmt.models import model
from opennmt.models import sequence_tagger
from opennmt.models import sequence_to_sequence
from opennmt.models import transformer
from opennmt.utils import misc
import opennmt as onmt
import logging
tf.get_logger().setLevel(logging.INFO)



class GPT2Small(language_model.LanguageModel):
  """GPT-2 language model (small version) as described in:
  https://d4mucfpksywv.cloudfront.net/better-language-models/language-models.pdf
  """

  def __init__(self):
    super(GPT2Small, self).__init__(
        decoder=decoders.SelfAttentionDecoder(
            num_layers=12,
            num_units=768,
            num_heads=12,
            ffn_inner_dim=3072,
            ffn_activation=layers.gelu,
            position_encoder_class=lambda: layers.PositionEmbedder(maximum_position=1024),
            num_sources=0),
        embedding_size=768)

  def auto_config(self, num_replicas=1):
    config = super(GPT2Small, self).auto_config(num_replicas=num_replicas)
    return misc.merge_dict(config, {
        "params": {
            "average_loss_in_time": True,
            "optimizer": "Adam",
            "learning_rate": 2.5e-4,
            "decay_type": "CosineAnnealing",
            "decay_params": {
                "max_step": 1000000,
                "warmup_steps": 2000,
            }
        },
        "train": {
            # Below options are from GPT-1.
            "batch_size": 64,
            "maximum_features_length": 512
        }
    })



def main():
    src =  folderpath + "train-source.txt" #Path to the source file.
    tgt = folderpath + "train-target.txt" #Path to the target file.
    src_vocab =folderpath + "train-src-vocab" #Path to the source vocabulary.
    tgt_vocab =folderpath + "train-tgt-vocab" #Path to the target vocabulary.
    model_dir =folderpath + "model_gpt/" #Directory where checkpoint are written.
    eval_features_file = folderpath + "val-source.txt"
    eval_labels_file = folderpath + "val-target.txt"

    model_dir = folderpath + "model_gpt/"
    config = {
       "data": {
          "eval_features_file": eval_features_file,
          "train_features_file": src,
          "vocabulary": src_vocab
       },
       "eval": {
          "batch_size": 32,
          "eval_delay": 1200,
          "exporter": "last",
          "exporters": "last",
          "num_threads": 1,
          "prefetch_buffer_size": 1,
          "save_eval_predictions": False
       },
       "infer": {
          "batch_size": 32,
          "bucket_width": 5,
          "n_best": 1,
          "num_threads": 1,
          "prefetch_buffer_size": 1,
          "with_scores": True
       },
       "model_dir": model_dir,
       "params": {
          "average_loss_in_time": True,
          "beam_width": 5,
          "decay_params": {
             "max_step": 1000000,
             "warmup_steps": 8000
          },
          "gradients_accum": 1,
          "label_smoothing": 0.1,
          "learning_rate": 2,
          "length_penalty": 0.6,
          "maximum_iterations": 50,
          "minimum_decoding_length": 0,
          "weight_decay": 0.01
       },
       "score": {
          "batch_size": 64
       },
       "train": {
          "average_last_checkpoints": 8,
          "batch_size": 4096,
          "batch_type": "tokens",
          "bucket_width": 8,
          "keep_checkpoint_max": 8,
          "maximum_features_length": 256,
          "maximum_labels_length": 256,
          "num_threads": 8,
          "prefetch_buffer_size": 4,
          "sample_buffer_size": 100000,
          "save_checkpoints_steps": 5000,
          "save_summary_steps": 100,
          "train_steps": 10000
       }

    }
    

    
    """
    Different Models Availabe :
    Transformer, TransformerBase, TransformerBaseRelative, TransformerBigRelative, TransformerBig, 
    TransformerRelative, GPT2Small, SequenceToSequenceInputter, SequenceClassifier, SequenceGenerator, SequenceToSequence, 
    SequenceTagger 
    
    
    """
    
    
    model = onmt.models.GPT2Small()
    runner = onmt.Runner(model, config, auto_config= True)
    runner.train(with_eval=True)
    tf.saved_model.save(model, model_dir, signatures=model.serve_function())
    
if __name__ == "__main__":
    main()
```

**Comment by guillaumekln** [comment]
The learning rate you set in the configuration is too large. You can see the default learning rate in GPT2Small is `2.5e-4` but you then set `2`.
