### ISSUE TITLE
The update on sacrebleu presents error

### ISSUE THREAD

**Issue by abumafrim** [OpenNMT/OpenNMT-tf#776]
Traceback (most recent call last):
  File "/usr/local/bin/onmt-main", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/opennmt/bin/main.py", line 231, in main
    hvd=hvd)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/runner.py", line 245, in train
    moving_average_decay=train_config.get("moving_average_decay"))
  File "/usr/local/lib/python3.6/dist-packages/opennmt/training.py", line 118, in __call__
    early_stop = self._evaluate(evaluator, step, moving_average=moving_average)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/training.py", line 150, in _evaluate
    evaluator(step)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/evaluation.py", line 317, in __call__
    score = scorer(self._labels_file, output_path)
  File "/usr/local/lib/python3.6/dist-packages/opennmt/utils/scorers.py", line 83, in __call__
    bleu = sacrebleu.corpus_bleu(sys_stream, [ref_stream], force=True)
  File "/usr/local/lib/python3.6/dist-packages/sacrebleu/compat.py", line 36, in corpus_bleu
    sys_stream, ref_streams, use_effective_order=use_effective_order)
  File "/usr/local/lib/python3.6/dist-packages/sacrebleu/metrics/bleu.py", line 276, in corpus_score
    if any(len(ref_stream) != len(sys_stream) for ref_stream in ref_streams):
  File "/usr/local/lib/python3.6/dist-packages/sacrebleu/metrics/bleu.py", line 276, in <genexpr>
    if any(len(ref_stream) != len(sys_stream) for ref_stream in ref_streams):
TypeError: object of type 'GFile' has no len()

**Comment by guillaumekln** [comment]
If using the OpenNMT-tf 2.14.0, please install the previous version of SacreBLEU:

```
pip install sacrebleu==1.4.14
```

This issue is already fixed on master https://github.com/OpenNMT/OpenNMT-tf/commit/717e8b7cb67b09147f4200a1fa9a51ccef3aa7ea, so let me close this issue.
