### ISSUE TITLE
Model diverged with loss = NaN occurs frequently late in training.

### ISSUE THREAD

**Issue by FPBHW** [OpenNMT/OpenNMT-tf#798]
Hi,

we seem to encounter the same issue as [744](https://github.com/OpenNMT/OpenNMT-tf/issues/744).

This happens in multiple model trainings, after many iterations of stable numerical conditions, and has started since we upgraded to OpenNMT-tf 2.14.0

Typical stack trace:
```
INFO:tensorflow:Step = 1055200 ; steps/s = 1.26, source words/s = 86443, target words/s = 115981 ; Learning rate = 0.000061 ; Loss = 2.082955
INFO:tensorflow:Step = 1055300 ; steps/s = 1.26, source words/s = 86334, target words/s = 115891 ; Learning rate = 0.000061 ; Loss = 2.076958
INFO:tensorflow:Step = 1055400 ; steps/s = 1.25, source words/s = 86131, target words/s = 115615 ; Learning rate = 0.000061 ; Loss = 2.085421
INFO:tensorflow:Step = 1055500 ; steps/s = 1.25, source words/s = 86073, target words/s = 115512 ; Learning rate = 0.000061 ; Loss = 2.122291
INFO:tensorflow:Step = 1055600 ; steps/s = 1.26, source words/s = 86845, target words/s = 116595 ; Learning rate = 0.000061 ; Loss = 2.073033
INFO:tensorflow:Step = 1055700 ; steps/s = 1.27, source words/s = 87238, target words/s = 117090 ; Learning rate = 0.000061 ; Loss = 2.089430
INFO:tensorflow:Step = 1055800 ; steps/s = 1.24, source words/s = 85450, target words/s = 114675 ; Learning rate = 0.000061 ; Loss = 2.087307
INFO:tensorflow:Step = 1055900 ; steps/s = 1.26, source words/s = 86461, target words/s = 116002 ; Learning rate = 0.000061 ; Loss = 2.167119
INFO:tensorflow:Step = 1056000 ; steps/s = 1.26, source words/s = 86385, target words/s = 115987 ; Learning rate = 0.000061 ; Loss = 2.168033
INFO:tensorflow:Step = 1056100 ; steps/s = 1.27, source words/s = 86947, target words/s = 116602 ; Learning rate = 0.000061 ; Loss = 2.103735
INFO:tensorflow:Step = 1056200 ; steps/s = 1.24, source words/s = 85244, target words/s = 114325 ; Learning rate = 0.000061 ; Loss = 2.171240
INFO:tensorflow:Step = 1056300 ; steps/s = 1.26, source words/s = 86715, target words/s = 116301 ; Learning rate = 0.000061 ; Loss = 2.082136
Traceback (most recent call last):
  File "/root/miniconda3/bin/onmt-main", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 231, in main
    hvd=hvd)
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/runner.py", line 245, in train
    moving_average_decay=train_config.get("moving_average_decay"))
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/training.py", line 98, in __call__
    raise RuntimeError("Model diverged with loss = NaN.")
RuntimeError: Model diverged with loss = NaN.
```

The learning rate and loss are well-behaved, and have been for over 1M iterations, hence numerical issues are not likely to blame here, arguably the same can be said for [744](https://github.com/OpenNMT/OpenNMT-tf/issues/744) albeit at a larger scale.

Is it possible that there is another issue akin to [discussion](https://forum.opennmt.net/t/runtimeerror-model-diverged-with-loss-nan/3259/7) and [patch](https://github.com/OpenNMT/OpenNMT-tf/pull/545) ?

Many thanks in advance

**Comment by guillaumekln** [comment]
Hi,

What version was used before updating to OpenNMT-tf 2.14.0?

Can you post the full training logs?

**Comment by FPBHW** [comment]
We previously used 2.4.0 for several months, and did not observe this behaviour.

**Comment by FPBHW** [comment]
Training log attached:
[training-log.zip](https://github.com/OpenNMT/OpenNMT-tf/files/6043252/training-log.zip)

**Comment by guillaumekln** [comment]
Thanks for the logs.

> This happens in multiple model trainings

Does it happen after the same number of steps (approximately)?

**Comment by FPBHW** [comment]
> Thanks for the logs.
> 
> > This happens in multiple model trainings
> 
> Does it happen after the same number of steps (approximately)?

Not really ... It's variable but it does happen fairly late in training in the cases that we've seen. It can be after 600k, or 1M....

**Comment by guillaumekln** [comment]
Did you try to continue from the last checkpoint? If yes, does the error happen again after continuing and approximately at the same step where it originally happened, or does it seem like the training can continue for another 600k+ steps?

Also what TensorFlow versions did you use before and now?

**Comment by FPBHW** [comment]
Hi, here are a few cases:
1) Model trained from scratch upto 360k, then NaN. Restored from checkpoint, trained until   418k, another NaN.
2) Model trained from scratch upto 670k, then NaN. Restored from checkpoint, trained until 1.056M, another NaN. 

That is, the training does not crash twice at nor near the same iteration. We use default training settings, and the loss and learning rate are well behaved, as in the log file shared before.

The current pip package for TF is"tensorflow-2.3.1" Before, it was tensorflow-gpu-2.0.0

**Comment by guillaumekln** [comment]
Thanks for all the info.

This is likely related to mixed precision training but it's hard to pinpoint the exact issue. I will check if I can reproduce a similar error. You could start a training without mixed precision and confirm that it works without issues.

While very unlikely, a server or GPU issue is also possible. In the past we had random NaN loss errors happening on a specific V100 node after we updated the GPU driver. To exclude this issue you could run the same training with the previous OpenNMT-tf and TensorFlow versions.

**Comment by FPBHW** [comment]
We are running experiments without mixed precision. Somehow the trainings (both resumed and from scratch on the same data) got stuck trying to automatically determine the optimal batch size. Now trying with a fixed batch size.

Hope that this doesn't influence the results.

It will take a few days before we have results.

**Comment by FPBHW** [comment]
The experiment with 1) the same data as the crashing experiment, but 2)without mixed-precision, has now exceeded 1 million iterations without crashing.

Note: the batch size and random initialization etc would also be different. 

Please let us know if you need anything more!

**Comment by guillaumekln** [comment]
The latest version [2.17.0](https://github.com/OpenNMT/OpenNMT-tf/releases/tag/v2.17.0) contains changes related to mixed precision and loss management. You might want to give a try and see if it helps for your issue.

**Comment by guillaumekln** [comment]
Are you still facing this issue?

We are now training a lot of models in mixed precision and we did not face this issue so far. During this time we used TensorFlow 2.3 and OpenNMT-tf versions 2.17 to 2.20.
