### ISSUE TITLE
Transformer model training suddenly stops with a FileNotFoundError

### ISSUE THREAD

**Issue by GalleonChestnut** [OpenNMT/OpenNMT-tf#809]
I am training a Dual-source transformer model on Google Colab and while training it suddenly stops with the follwing error message,

```
> Traceback (most recent call last):
  File "/usr/local/bin/onmt-main", line 33, in <module>
    sys.exit(load_entry_point('OpenNMT-tf==2.16.0', 'console_scripts', 'onmt-main')())
  File "/usr/local/lib/python3.7/dist-packages/OpenNMT_tf-2.16.0-py3.7.egg/opennmt/bin/main.py", line 327, in main
    hvd=hvd,
  File "/usr/local/lib/python3.7/dist-packages/OpenNMT_tf-2.16.0-py3.7.egg/opennmt/runner.py", line 281, in train
    moving_average_decay=train_config.get("moving_average_decay"),
  File "/usr/local/lib/python3.7/dist-packages/OpenNMT_tf-2.16.0-py3.7.egg/opennmt/training.py", line 141, in __call__
    self._save_checkpoint(step, moving_average=moving_average)
  File "/usr/local/lib/python3.7/dist-packages/OpenNMT_tf-2.16.0-py3.7.egg/opennmt/training.py", line 186, in _save_checkpoint
    self._checkpoint.save(step)
  File "/usr/local/lib/python3.7/dist-packages/OpenNMT_tf-2.16.0-py3.7.egg/opennmt/utils/checkpoint.py", line 95, in save
    path = self._checkpoint_manager.save(checkpoint_number=step)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/checkpoint_management.py", line 819, in save
    self._record_state()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/checkpoint_management.py", line 728, in _record_state
    save_relative_paths=True)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/checkpoint_management.py", line 231, in update_checkpoint_state_internal
    last_preserved_timestamp=last_preserved_timestamp)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/checkpoint_management.py", line 117, in generate_checkpoint_state_proto
    model_checkpoint_path = os.path.relpath(model_checkpoint_path, save_dir)
  File "/usr/lib/python3.7/posixpath.py", line 475, in relpath
    start_list = [x for x in abspath(start).split(sep) if x]
  File "/usr/lib/python3.7/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

I tried re-reunning the same cell again and sometimes, it starts training right from the beginning or else, it keeps returning this error. I tried reseting the runtime and sometimes that works and sometimes it doesn't.  As I understood, this error occurs because a file is deleted but I did not manually deleted any file or directory. Please help me to resolve this issue. Thanks in advance

**Comment by guillaumekln** [comment]
Can you post the training command line and configuration? Are you saving checkpoints in a Google Drive?

**Comment by GalleonChestnut** [comment]
`!onmt-main --model dir/model_file.py --config dir/config_file.yaml train --with_eval`

This is the command I used for training and yes, I save checkpoints in Google Drive.

**Comment by guillaumekln** [comment]
Can you check if you get the same error when saving checkpoints in the Colab local storage instead of Google Drive?

**Comment by GalleonChestnut** [comment]
I trained the model for 15000 iterations while saving the checkpoints in the Colab local storage and later copied them to the Google Drive. The above error didn't arise when I changed the location to save checkpoints from Google Drive to Colab local storage. Thank you so much.
