### ISSUE TITLE
Exception: SGD optimizer receives "beta1" which is not set

### ISSUE THREAD

**Issue by FPBHW** [OpenNMT/OpenNMT-tf#885]
Hi,

the "SGD" optimizer cannot be instantiated because it receives parameters specific to Adam, even though these are not in the configuration file.

From the config file:
```
params:
  optimizer: SGD
  optimizer_params:
    momentum: 0
  minimum_learning_rate: 0.0001
```

The error:
```
Traceback (most recent call last):

  File "/root/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 363, in <module>
    main()
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 326, in main
    hvd=hvd,
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/runner.py", line 204, in train
    optimizer = model.get_optimizer()
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/models/model.py", line 230, in get_optimizer
    optimizer_name, learning_rate, **optimizer_params
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/optimizers/utils.py", line 66, in make_optimizer
    optimizer = optimizer_class(learning_rate=learning_rate, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/gradient_descent.py", line 109, in __init__
    super(SGD, self).__init__(name, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 340, in __init__
    "passed to optimizer: " + str(k))
TypeError: Unexpected keyword argument passed to optimizer: beta_1
```

Version information:
`Successfully installed OpenNMT-tf-2.20.1 ctranslate2-2.4.0 portalocker-2.0.0 pyonmttok-1.28.0 pyyaml-5.4.1 rouge-1.0.1 sacrebleu-1.5.1 tensorflow-addons-0.13.0 typeguard-2.12.1`

**Comment by guillaumekln** [comment]
You are probably using `--auto_config` which comes with this optimizer setttings:

```yaml
params:
  optimizer: LazyAdam
  optimizer_params:
    beta_1: 0.9
    beta_2: 0.998
```

Your configuration is then merged into this automatic configuration:

```yaml
params:
  optimizer: SGD
  optimizer_params:
    momentum: 0
    beta_1: 0.9
    beta_2: 0.998
```

If you want to change the optimizer to SGD, it is currently not possible to use `--auto_config`.

**Comment by guillaumekln** [comment]
The fix I'm proposing is to disable the merge for the field `optimizer_params` (same for `decay_params`). With this change the optimizer parameters coming from `--auto_config` will be fully overridden by the parameters you provided.
