### ISSUE TITLE
SGD does not receive parameters

### ISSUE THREAD

**Issue by FPBHW** [OpenNMT/OpenNMT-tf#887]
Using SGD results in an exception during initialization in `OpenNMT-tf-2.20.1`.

The config file:
```
params:
  optimizer: SGD
  optimizer_params:
    learning_rate: 0.001
    clipnorm: 0.05
  minimum_learning_rate: 0.0001
```

Leads to:
```
2021-10-01 23:18:18.082000: I main.py:326] Trying training with batch size 16...
2021-10-01 23:18:25.907000: I main.py:326] ... failed.
2021-10-01 23:18:25.908000: E main.py:326] Last training attempt exited with an error:
"""
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/miniconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 363, in <module>
    main()
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/bin/main.py", line 326, in main
    hvd=hvd,
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/runner.py", line 204, in train
    optimizer = model.get_optimizer()
  File "/root/miniconda3/lib/python3.7/site-packages/opennmt/models/model.py", line 215, in get_optimizer
    learning_rate = tf.constant(params["learning_rate"], dtype=tf.float32)
KeyError: 'learning_rate'
```

The learning rate is present in the config file, and has a default value in keras, so arguably should not need to be in the config file.

**Comment by guillaumekln** [comment]
The learning rate should be set outside the `optimizer_params` block:

```yaml
params:
  optimizer: SGD
  optimizer_params:
    clipnorm: 0.05
  learning_rate: 0.001
  minimum_learning_rate: 0.0001
```

See the reference configuration file: https://opennmt.net/OpenNMT-tf/configuration.html#reference

**Comment by FPBHW** [comment]
Thank you! Will try.

**Comment by FPBHW** [comment]
I also notice:
```
021-10-04 16:05:54.530000: I main.py:326] Searching the largest batch size between 1 and 512 with a precision of 16...
2021-10-04 16:05:54.536000: I main.py:326] Trying training with batch size 256...
```

Usually batch sizes are between 10k and 16k, any idea why the batch size is so much smaller ? Only change here is the switch to SGD, when using the same stack with `--auto_config` the batch sizes are much larger.

**Comment by FPBHW** [comment]
The hardware supporting larger batch sizes is present and detected:
```
2021-10-04 16:05:51.053434: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0, 1, 2, 3, 4, 5, 6, 7
2021-10-04 16:05:51.053479: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
2021-10-04 16:05:54.474545: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-10-04 16:05:54.474598: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 1 2 3 4 5 6 7 
2021-10-04 16:05:54.474607: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N Y Y Y Y Y Y Y 
2021-10-04 16:05:54.474613: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 1:   Y N Y Y Y Y Y Y 
2021-10-04 16:05:54.474619: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 2:   Y Y N Y Y Y Y Y 
2021-10-04 16:05:54.474625: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 3:   Y Y Y N Y Y Y Y 
2021-10-04 16:05:54.474630: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 4:   Y Y Y Y N Y Y Y 
2021-10-04 16:05:54.474636: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 5:   Y Y Y Y Y N Y Y 
2021-10-04 16:05:54.474641: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 6:   Y Y Y Y Y Y N Y 
2021-10-04 16:05:54.474647: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 7:   Y Y Y Y Y Y Y N 
2021-10-04 16:05:54.490648: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30126 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:2d:00.0, compute capability: 7.0)
2021-10-04 16:05:54.496100: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 30126 MB memory) -> physical GPU (device: 1, name: Tesla V100-SXM2-32GB, pci bus id: 0000:32:00.0, compute capability: 7.0)

2021-10-04 16:05:54.500196: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 30126 MB memory) -> physical GPU (device: 2, name: Tesla V100-SXM2-32GB, pci bus id: 0000:5b:00.0, compute capability: 7.0)

2021-10-04 16:05:54.503766: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 30126 MB memory) -> physical GPU (device: 3, name: Tesla V100-SXM2-32GB, pci bus id: 0000:5f:00.0, compute capability: 7.0)

2021-10-04 16:05:54.507699: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 30126 MB memory) -> physical GPU (device: 4, name: Tesla V100-SXM2-32GB, pci bus id: 0000:b5:00.0, compute capability: 7.0)
2021-10-04 16:05:54.511616: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 30126 MB memory) -> physical GPU (device: 5, name: Tesla V100-SXM2-32GB, pci bus id: 0000:be:00.0, compute capability: 7.0)
2021-10-04 16:05:54.515134: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:6 with 30126 MB memory) -> physical GPU (device: 6, name: Tesla V100-SXM2-32GB, pci bus id: 0000:e1:00.0, compute capability: 7.0)
2021-10-04 16:05:54.519957: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 30126 MB memory) -> physical GPU (device: 7, name: Tesla V100-SXM2-32GB, pci bus id: 0000:e9:00.0, compute capability: 7.0)
2021-10-04 16:05:54.530000: I main.py:326] Searching the largest batch size between 1 and 512 with a precision of 16...
2021-10-04 16:05:54.536000: I main.py:326] Trying training with batch size 256...
```

**Comment by guillaumekln** [comment]
There are 2 ways to define the batch size. It is either the number of tokens or the number of examples.

Transformer with `--auto_config` uses the number of tokens, but without `--auto_config` the number of examples is used by default since this how the batch size is more generally defined.

It seems like it would be easier to use `--auto_config` directly. Why do you need to use the SGD optimizer?

**Comment by FPBHW** [comment]
Basically I am debugging the learning process and testing a hypothesis about the behavior of the learner. This requires me to use a different learner to see if the same behavior is observed.

**Comment by guillaumekln** [comment]
Let me close this issue as there is no bug with the code.

* `learning_rate` should be defined in the `params` block, not `optimizer_params`
* without `--auto_config`, the default `batch_type` is "examples", not "tokens", which explains the smaller value.
