### ISSUE TITLE
RsqrtDecay fails when decay_params scale is configured

### ISSUE THREAD

**Issue by Dagamies** [OpenNMT/OpenNMT-tf#923]
With following configuration:
```
 decay_type: RsqrtDecay
 decay_params:
   warmup_steps: 10000
   scale: 4
```
Training fails to start with an error:
```
Traceback (most recent call last):
  File "opennmt/bin/main.py", line 350, in <module>
    main()
  File "opennmt/bin/main.py", line 308, in main
    runner.train(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/runner.py", line 207, in train
    optimizer = model.get_optimizer()
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/models/model.py", line 338, in get_optimizer
    learning_rate = schedules.make_learning_rate_schedule(
  File "/ai/onmt/onmt-2240/OpenNMT-tf/opennmt/schedules/lr_schedules.py", line 75, in make_learning_rate_schedule
    schedule = schedule_class(initial_learning_rate, **schedule_params)
TypeError: __init__() got multiple values for argument 'scale'
```
A small change to RsqrtDecay function will fix the issue. It seems that 1st parameter to __init__ is not scale but lr, currently:
```
class RsqrtDecay(tf.keras.optimizers.schedules.LearningRateSchedule):
    """Decay based on the reciprocal of the step square root."""

    def __init__(self ,scale, warmup_steps):
```
If changed to will fix the issue:
```
class RsqrtDecay(tf.keras.optimizers.schedules.LearningRateSchedule):
    """Decay based on the reciprocal of the step square root."""

    def __init__(self, lr ,scale, warmup_steps):
```

**Comment by guillaumekln** [comment]
In the current implementation, the first argument of learning rate schedules is always the `learning_rate` value defined in the configuration. Some schedules will use this value as the initial learning rate, other schedules will use the value as a scale constant. We could probably improve this behavior.

For now, you could just remove the `scale` parameter and set `learning_rate` instead:

```yaml
params:
  learning_rate: 4
  decay_type: RsqrtDecay
  decay_params:
    warmup_steps: 10000
```

**Comment by guillaumekln** [comment]
I made some changes so that your initial configuration is now valid.
