### ISSUE TITLE
An input error occurred while expanding the dataset

### ISSUE THREAD

**Issue by copperdong** [OpenNMT/OpenNMT-tf#979]
When I tried to expand the dataset, an input error occurred.
 Is there a problem with my dataset？
 But I don't know how to modify it.  
Can someone help me analyze it?
Thanks
`2022-10-22 21:11:06.016000: I training.py:192] Evaluation predictions saved to checkpoint_align_biggest/eval/predictions.txt.10000                                                                                                     [0/33618]
2022-10-22 21:11:21.079000: I training.py:192] Evaluation result for step 10000: loss = 3.388197 ; perplexity = 29.612505 ; bleu = 13.022570
2022-10-22 21:13:31.446000: I runner.py:289] Step = 10100 ; steps/s = 0.77, source words/s = 20073, target words/s = 17304 ; Learning rate = 0.000879 ; Loss = 3.466225
2022-10-22 21:15:40.987000: I runner.py:289] Step = 10200 ; steps/s = 0.77, source words/s = 20215, target words/s = 17405 ; Learning rate = 0.000875 ; Loss = 3.304288
2022-10-22 21:17:50.403000: I runner.py:289] Step = 10300 ; steps/s = 0.77, source words/s = 20237, target words/s = 17413 ; Learning rate = 0.000871 ; Loss = 3.433897
Traceback (most recent call last):
  File "/home/yons/anaconda3/bin/onmt-main", line 8, in <module>
    sys.exit(main())
  File "/home/yons/anaconda3/lib/python3.9/site-packages/opennmt/bin/main.py", line 318, in main
    runner.train(
  File "/home/yons/anaconda3/lib/python3.9/site-packages/opennmt/runner.py", line 289, in train
    summary = trainer(
  File "/home/yons/anaconda3/lib/python3.9/site-packages/opennmt/training.py", line 109, in __call__
    for i, loss in enumerate(
  File "/home/yons/anaconda3/lib/python3.9/site-packages/opennmt/training.py", line 248, in _steps
    loss = forward_fn()
  File "/home/yons/anaconda3/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/yons/anaconda3/lib/python3.9/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

2 root error(s) found.
  (0) INVALID_ARGUMENT:  Input to reshape is a tensor with 61 values, but the requested shape requires a multiple of 2
         [[{{node Reshape}}]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_10]]
  (1) INVALID_ARGUMENT:  Input to reshape is a tensor with 61 values, but the requested shape requires a multiple of 2
         [[{{node Reshape}}]]
         [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference__forward_38057]`

**Comment by copperdong** [comment]
There is a problem with 5 rows of data
